### ISSUE TITLE
v1.3.4B1 - Italian currency entry not retaining currency settings 10.000,00

### ISSUE THREAD

**Issue by siowena** [moneymanagerex/moneymanagerex#2335]
**Describe the bug**
Win10 v1.3.4.Beta1 - Italian users are reporting they cannot set entry to italian format when using Euro.  Defaults to entry of numbers 1,000.00 and not 1.000,00 even through they've tried to set current decimal and separator values on Euro.

**To Reproduce**

**Expected behavior**
Setting Euro currency decimal & separator should allow them to enter transactions with italian format.

**Screenshots**
TBC

**Additional** see https://forum.moneymanagerex.org/viewtopic.php?f=10&t=9090

**Your OS:**
- [X] Windows 10

**MMEX version:**
- [x] 1.3.4 Beta

**Comment by vomikan** [comment]
This bug possible has fixed in
mmex 1.3.4-beta.2 release with DB v.7

![image](https://user-images.githubusercontent.com/6836805/77311478-36d4aa80-6d11-11ea-9b2b-55f848e80d0a.png)

**Comment by siowena** [comment]
OK, been playing around
- On Windows PC, added a new user.
- Logged in as user and set the user to Keyboard=Italian; Language=Italian; Regional Format=Italian (Italy)
(see screenshots attached).
- Downloaded v1.3.4beta2 from GitHub and installed
- Started MMEX created a new DB with Base currency Euro; 1 Checking Acc
- Set the Euro to "," for decimal and "." for separator
- New Transaction, the decimal just didn't work always set to ,00

- after trying a few things found the following
- exit MMEX
- set Regioal format to "English (United Kingdom)'
- start MMEX and open the same DB
- enter transaction, decimals worked  1,45
- end MMEX
- set Regional format back to Italian and tried MMEX - same decimal issue returned 

![Annotazione 2020-03-30 213410](https://user-images.githubusercontent.com/44472390/77943790-e50ec000-72ce-11ea-9461-98314d7ad4f7.png)
![Annotazione 2020-03-30 213449](https://user-images.githubusercontent.com/44472390/77943794-e6d88380-72ce-11ea-84ee-03b0e1ff8440.png)

**Comment by siowena** [comment]
Still exists in mmex-1.3.4.rc1-win64.exe

As Italian user, switching to Ingese (USA) - the , decimal works. As Italia the 1,56 become 1,00 on leaving the amount field.

(Note: I think this also impacts French users as a forum topic has been raised).

![Screenshot (1)](https://user-images.githubusercontent.com/44472390/77990724-20db7100-7333-11ea-9fde-0b7e2d2f89bb.png)
![Screenshot (2)](https://user-images.githubusercontent.com/44472390/77990727-233dcb00-7333-11ea-846c-e57186f99c4d.png)

**Comment by siowena** [comment]
I'll give rc2 a test

**Comment by siowena** [comment]
This seems to work when I use the users on my PC setup as French and Italian.  (1.3.4rc2)

See images on Italian Settings

![Annotazione 2020-04-04 103933](https://user-images.githubusercontent.com/44472390/78420882-5ef2d080-7664-11ea-9ffb-7b6bb1684a8e.png)
![Annotazione 2020-04-04 104025](https://user-images.githubusercontent.com/44472390/78420883-60bc9400-7664-11ea-9b5a-f29f01a1cd1f.png)
