### ISSUE TITLE
Constant crashing with a Debug report window

### ISSUE THREAD

**Issue by feimosi** [moneymanagerex/moneymanagerex#2399]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Arch Linux
- Check MMEX version
  - [X] 1.3.3-3
  - [ ] 1.2.x
  - [ ] 1.1 or older

Very often, when opening different report views the app crashes with the following window. If I restart the app, I can open that report easily but then after switching between views (just 2-3) it'll crash again. This happens for both built-in and custom reports.

![image](https://user-images.githubusercontent.com/5721520/79744742-2f4ff380-8307-11ea-8d87-7a4a707e685b.png)

<details>
<summary>Here's the file contents:</summary>

```
<?xml version="1.0" encoding="UTF-8"?>
<report version="1.0" kind="exception">
  <system description="Linux 5.6.4-arch1-1 x86_64"/>
  <modules>
    <module path="/usr/bin/mmex" address="555fb7433000" size="000ea000"/>
    <module path="/usr/bin/mmex" address="555fb79b7000" size="00202000"/>
    <module path="/usr/bin/mmex" address="555fb7be9000" size="0001b000"/>
    <module path="[heap]" address="555fb870f000" size="0126b000"/>
    <module path="/usr/lib/librsvg-2.so.2.47.0" address="7f28040a9000" size="0009e000" version="2.47.0"/>
    <module path="/usr/lib/librsvg-2.so.2.47.0" address="7f280433e000" size="00135000" version="2.47.0"/>
    <module path="/usr/lib/librsvg-2.so.2.47.0" address="7f28044fc000" size="00001000" version="2.47.0"/>
    <module path="/usr/share/icons/Numix/icon-theme.cache" address="7f2806253000" size="000ad000"/>
    <module path="/usr/share/icons/Numix-Square/icon-theme.cache" address="7f28064aa000" size="00056000"/>
    <module path="/memfd:WebKitSharedMemory" address="7f2806611000" size="00001000"/>
    <module path="/usr/share/icons/hicolor/icon-theme.cache" address="7f2806613000" size="00006000"/>
    <module path="/usr/share/locale/en_GB/LC_MESSAGES/WebKit2GTK-4.0.mo" address="7f280666d000" size="0000c000"/>
    <module path="/usr/share/fonts/cantarell/Cantarell-Bold.otf" address="7f2806e85000" size="00025000"/>
    <module path="/usr/share/mime/mime.cache" address="7f2806ecf000" size="00025000"/>
    <module path="/usr/share/locale/en_GB/LC_MESSAGES/glib20.mo" address="7f2806f5f000" size="0001f000"/>
    <module path="/SYSV00000000" address="7f2807f80000" size="00080000"/>
    <module path="/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so" address="7f280c000000" size="00001000" version="svg"/>
    <module path="/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so" address="7f280c002000" size="00001000" version="svg"/>
    <module path="/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so" address="7f280c004000" size="00001000" version="svg"/>
    <module path="/usr/share/fonts/TTF/Vera.ttf" address="7f280c006000" size="00011000"/>
    <module path="/usr/share/fonts/cantarell/Cantarell-Regular.otf" address="7f280c028000" size="00024000"/>
    <module path="/usr/lib/libnss_dns-2.31.so" address="7f280c04e000" size="00004000" version="2.31"/>
    <module path="/usr/lib/libnss_dns-2.31.so" address="7f280c053000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libnss_resolve.so.2" address="7f280c055000" size="00007000" version="2"/>
    <module path="/usr/lib/libnss_resolve.so.2" address="7f280c08e000" size="00011000" version="2"/>
    <module path="/usr/lib/libnss_resolve.so.2" address="7f280c0a0000" size="00003000" version="2"/>
    <module path="/usr/lib/libnss_myhostname.so.2" address="7f280c0a5000" size="00003000" version="2"/>
    <module path="/usr/lib/libnss_myhostname.so.2" address="7f280c0b2000" size="00008000" version="2"/>
    <module path="/usr/lib/libnss_myhostname.so.2" address="7f280c0bd000" size="00001000" version="2"/>
    <module path="/usr/lib/libnss_mymachines.so.2" address="7f280c0c5000" size="00033000" version="2"/>
    <module path="/usr/lib/libnss_mymachines.so.2" address="7f280c109000" size="00001000" version="2"/>
    <module path="/usr/lib/libnss_mymachines.so.2" address="7f280c10d000" size="00001000" version="2"/>
    <module path="/usr/share/fonts/cantarell/Cantarell-Regular.otf" address="7f280c110000" size="00024000"/>
    <module path="/usr/share/locale/en_GB/LC_MESSAGES/gdk-pixbuf.mo" address="7f280c14e000" size="00006000"/>
    <module path="/home/feimosi/.cache/fontconfig/dd73f916258025c47c443714c9d559eb-le64.cache-7" address="7f280c35f000" size="00042000"/>
    <module path="/var/cache/fontconfig/b67b32625a2bb51b023d3814a918f351-le64.cache-7" address="7f280c3a8000" size="00005000"/>
    <module path="/var/cache/fontconfig/f6b893a7224233d96cb72fd88691c0b4-le64.cache-7" address="7f280c3bb000" size="00010000"/>
    <module path="/usr/lib/libnss_files-2.31.so" address="7f280c436000" size="00003000" version="2.31"/>
    <module path="/usr/lib/libnss_files-2.31.so" address="7f280c440000" size="00002000" version="2.31"/>
    <module path="/usr/lib/libnss_files-2.31.so" address="7f280c443000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libogg.so.0.8.4" address="7f280c44a000" size="00002000" version="0.8.4"/>
    <module path="/usr/lib/libogg.so.0.8.4" address="7f280c44f000" size="00003000" version="0.8.4"/>
    <module path="/usr/lib/libogg.so.0.8.4" address="7f280c453000" size="00001000" version="0.8.4"/>
    <module path="/usr/lib/libvorbis.so.0.4.8" address="7f280c455000" size="0002a000" version="0.4.8"/>
    <module path="/usr/lib/libvorbis.so.0.4.8" address="7f280c67f000" size="00001000" version="0.4.8"/>
    <module path="/usr/lib/libtdb.so.1.4.3" address="7f280c681000" size="00004000" version="1.4.3"/>
    <module path="/usr/lib/libtdb.so.1.4.3" address="7f280c692000" size="00006000" version="1.4.3"/>
    <module path="/usr/lib/libtdb.so.1.4.3" address="7f280c699000" size="00001000" version="1.4.3"/>
    <module path="/usr/lib/libvorbisfile.so.3.3.7" address="7f280c6a1000" size="00200000" version="3.3.7"/>
    <module path="/usr/lib/libvorbisfile.so.3.3.7" address="7f280c8a2000" size="00001000" version="3.3.7"/>
    <module path="/var/cache/fontconfig/210c0516121708a580e22e6b1f9a103a-le64.cache-7" address="7f280c8a5000" size="0000d000"/>
    <module path="/var/cache/fontconfig/6ba42ae0000f58711b5caaf10d690066-le64.cache-7" address="7f280c918000" size="00005000"/>
    <module path="/usr/lib/libltdl.so.7.3.1" address="7f280c91f000" size="00005000" version="7.3.1"/>
    <module path="/usr/lib/libltdl.so.7.3.1" address="7f280c926000" size="00001000" version="7.3.1"/>
    <module path="/usr/lib/libltdl.so.7.3.1" address="7f280c928000" size="00001000" version="7.3.1"/>
    <module path="/usr/lib/libcanberra.so.0.2.5" address="7f280c92c000" size="0000a000" version="0.2.5"/>
    <module path="/usr/lib/libcanberra.so.0.2.5" address="7f280c93a000" size="00001000" version="0.2.5"/>
    <module path="/usr/lib/libcanberra.so.0.2.5" address="7f280c93c000" size="00001000" version="0.2.5"/>
    <module path="/usr/lib/libcanberra-gtk3.so.0.1.9" address="7f280c93f000" size="00002000" version="0.1.9"/>
    <module path="/usr/lib/libcanberra-gtk3.so.0.1.9" address="7f280c942000" size="00001000" version="0.1.9"/>
    <module path="/usr/lib/gvfs/libgvfscommon.so" address="7f280d967000" size="00013000"/>
    <module path="/usr/lib/gvfs/libgvfscommon.so" address="7f280d994000" size="0000d000"/>
    <module path="/usr/lib/gvfs/libgvfscommon.so" address="7f280d9a2000" size="00006000"/>
    <module path="/usr/lib/locale/locale-archive" address="7f280d9a9000" size="002e7000"/>
    <module path="/usr/lib/libcrypto.so.1.1" address="7f280dd05000" size="0019f000" version="1.1"/>
    <module path="/usr/lib/libcrypto.so.1.1" address="7f280df35000" size="0002c000" version="1.1"/>
    <module path="/usr/lib/libssl.so.1.1" address="7f280df67000" size="0001d000" version="1.1"/>
    <module path="/usr/lib/libssl.so.1.1" address="7f280dfd0000" size="0001a000" version="1.1"/>
    <module path="/usr/lib/libssl.so.1.1" address="7f280dfeb000" size="00009000" version="1.1"/>
    <module path="/usr/lib/libssh2.so.1.0.1" address="7f280dff8000" size="00007000" version="1.0.1"/>
    <module path="/usr/lib/libssh2.so.1.0.1" address="7f280e028000" size="0000d000" version="1.0.1"/>
    <module path="/usr/lib/libssh2.so.1.0.1" address="7f280e037000" size="00001000" version="1.0.1"/>
    <module path="/usr/lib/libnghttp2.so.14.19.0" address="7f280e03d000" size="00013000" version="14.19.0"/>
    <module path="/usr/lib/libnghttp2.so.14.19.0" address="7f280e05d000" size="00003000" version="14.19.0"/>
    <module path="/usr/lib/libcurl.so.4.6.0" address="7f280e061000" size="0000c000" version="4.6.0"/>
    <module path="/usr/lib/libcurl.so.4.6.0" address="7f280e0cf000" size="0001b000" version="4.6.0"/>
    <module path="/usr/lib/libcurl.so.4.6.0" address="7f280e0eb000" size="00003000" version="4.6.0"/>
    <module path="/usr/lib/libdebuginfod-0.178.so" address="7f280e0ef000" size="00002000" version="0.178"/>
    <module path="/usr/lib/libdebuginfod-0.178.so" address="7f280e0f3000" size="00001000" version="0.178"/>
    <module path="/usr/lib/libdebuginfod-0.178.so" address="7f280e0f5000" size="00001000" version="0.178"/>
    <module path="/usr/lib/liblz4.so.1.9.2" address="7f280e10a000" size="00003000" version="1.9.2"/>
    <module path="/usr/lib/liblz4.so.1.9.2" address="7f280e127000" size="00003000" version="1.9.2"/>
    <module path="/usr/lib/liblz4.so.1.9.2" address="7f280e12b000" size="00001000" version="1.9.2"/>
    <module path="/usr/lib/libidn2.so.0.3.7" address="7f280e12e000" size="00004000" version="0.3.7"/>
    <module path="/usr/lib/libidn2.so.0.3.7" address="7f280e14b000" size="00001000" version="0.3.7"/>
    <module path="/usr/lib/libunistring.so.2.1.0" address="7f280e14d000" size="00011000" version="2.1.0"/>
    <module path="/usr/lib/libunistring.so.2.1.0" address="7f280e193000" size="00137000" version="2.1.0"/>
    <module path="/usr/lib/libunistring.so.2.1.0" address="7f280e2ce000" size="00001000" version="2.1.0"/>
    <module path="/usr/lib/libkeyutils.so.1.9" address="7f280e2d1000" size="00002000" version="1.9"/>
    <module path="/usr/lib/libkeyutils.so.1.9" address="7f280e2d4000" size="00001000" version="1.9"/>
    <module path="/usr/lib/libkrb5support.so.0.1" address="7f280e2d6000" size="00003000" version="0.1"/>
    <module path="/usr/lib/libkrb5support.so.0.1" address="7f280e2e0000" size="00003000" version="0.1"/>
    <module path="/usr/lib/libkrb5support.so.0.1" address="7f280e2e4000" size="00001000" version="0.1"/>
    <module path="/usr/lib/libcom_err.so.2.1" address="7f280e2e7000" size="00001000" version="2.1"/>
    <module path="/usr/lib/libcom_err.so.2.1" address="7f280e2e9000" size="00001000" version="2.1"/>
    <module path="/usr/lib/libk5crypto.so.3.1" address="7f280e2ed000" size="00005000" version="3.1"/>
    <module path="/usr/lib/libk5crypto.so.3.1" address="7f280e30e000" size="0000d000" version="3.1"/>
    <module path="/usr/lib/libk5crypto.so.3.1" address="7f280e31d000" size="00001000" version="3.1"/>
    <module path="/usr/lib/libkrb5.so.3.3" address="7f280e341000" size="00068000" version="3.3"/>
    <module path="/usr/lib/libkrb5.so.3.3" address="7f280e3f2000" size="0000f000" version="3.3"/>
    <module path="/usr/lib/libudev.so.1.6.17" address="7f280e403000" size="00005000" version="1.6.17"/>
    <module path="/usr/lib/libudev.so.1.6.17" address="7f280e422000" size="0000a000" version="1.6.17"/>
    <module path="/usr/lib/libudev.so.1.6.17" address="7f280e42d000" size="00001000" version="1.6.17"/>
    <module path="/usr/lib/libelf-0.178.so" address="7f280e431000" size="00010000" version="0.178"/>
    <module path="/usr/lib/libelf-0.178.so" address="7f280e446000" size="00001000" version="0.178"/>
    <module path="/usr/lib/libbrotlicommon.so.1.0.7" address="7f280e448000" size="00001000" version="1.0.7"/>
    <module path="/usr/lib/libbrotlicommon.so.1.0.7" address="7f280e44a000" size="0001f000" version="1.0.7"/>
    <module path="/usr/lib/libbrotlicommon.so.1.0.7" address="7f280e46a000" size="00001000" version="1.0.7"/>
    <module path="/usr/lib/libsystemd.so.0.28.0" address="7f280e46d000" size="00012000" version="0.28.0"/>
    <module path="/usr/lib/libsystemd.so.0.28.0" address="7f280e4f0000" size="00025000" version="0.28.0"/>
    <module path="/usr/lib/libsystemd.so.0.28.0" address="7f280e519000" size="00001000" version="0.28.0"/>
    <module path="/usr/lib/libXdmcp.so.6.0.0" address="7f280e51b000" size="00002000" version="6.0.0"/>
    <module path="/usr/lib/libXdmcp.so.6.0.0" address="7f280e51f000" size="00002000" version="6.0.0"/>
    <module path="/usr/lib/libXdmcp.so.6.0.0" address="7f280e522000" size="00001000" version="6.0.0"/>
    <module path="/usr/lib/libXau.so.6.0.0" address="7f280e524000" size="00001000" version="6.0.0"/>
    <module path="/usr/lib/libXau.so.6.0.0" address="7f280e526000" size="00001000" version="6.0.0"/>
    <module path="/usr/lib/libdatrie.so.1.3.5" address="7f280e528000" size="00006000" version="1.3.5"/>
    <module path="/usr/lib/libdatrie.so.1.3.5" address="7f280e72d000" size="00001000" version="1.3.5"/>
    <module path="/usr/lib/libpsl.so.5.3.2" address="7f280e72f000" size="00002000" version="5.3.2"/>
    <module path="/usr/lib/libpsl.so.5.3.2" address="7f280e733000" size="0000d000" version="5.3.2"/>
    <module path="/usr/lib/libpsl.so.5.3.2" address="7f280e741000" size="00001000" version="5.3.2"/>
    <module path="/usr/lib/libgssapi_krb5.so.2.2" address="7f280e744000" size="0000c000" version="2.2"/>
    <module path="/usr/lib/libgssapi_krb5.so.2.2" address="7f280e788000" size="0000d000" version="2.2"/>
    <module path="/usr/lib/libgssapi_krb5.so.2.2" address="7f280e796000" size="00002000" version="2.2"/>
    <module path="/usr/lib/libgbm.so.1.0.0" address="7f280e799000" size="00003000" version="1.0.0"/>
    <module path="/usr/lib/libgbm.so.1.0.0" address="7f280e7a3000" size="00004000" version="1.0.0"/>
    <module path="/usr/lib/libgbm.so.1.0.0" address="7f280e7a8000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libdrm.so.2.4.0" address="7f280e7aa000" size="00005000" version="2.4.0"/>
    <module path="/usr/lib/libdrm.so.2.4.0" address="7f280e7b9000" size="00004000" version="2.4.0"/>
    <module path="/usr/lib/libdrm.so.2.4.0" address="7f280e7be000" size="00001000" version="2.4.0"/>
    <module path="/usr/lib/libgudev-1.0.so.0.2.0" address="7f280e7c3000" size="00004000" version="0.2.0"/>
    <module path="/usr/lib/libgudev-1.0.so.0.2.0" address="7f280e7c9000" size="00001000" version="0.2.0"/>
    <module path="/usr/lib/libgudev-1.0.so.0.2.0" address="7f280e7cb000" size="00001000" version="0.2.0"/>
    <module path="/usr/lib/libX11-xcb.so.1.0.0" address="7f280e7cd000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libX11-xcb.so.1.0.0" address="7f280e7cf000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libgstallocators-1.0.so.0.1602.0" address="7f280e7d3000" size="00002000" version="0.1602.0"/>
    <module path="/usr/lib/libgstallocators-1.0.so.0.1602.0" address="7f280e7d6000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgstallocators-1.0.so.0.1602.0" address="7f280e7d8000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/liborc-0.4.so.0.31.0" address="7f280e7e3000" size="00051000" version="0.31.0"/>
    <module path="/usr/lib/liborc-0.4.so.0.31.0" address="7f280e855000" size="00002000" version="0.31.0"/>
    <module path="/usr/lib/libdw-0.178.so" address="7f280e85b000" size="00015000" version="0.178"/>
    <module path="/usr/lib/libdw-0.178.so" address="7f280e8c0000" size="0002e000" version="0.178"/>
    <module path="/usr/lib/libdw-0.178.so" address="7f280e8ef000" size="00009000" version="0.178"/>
    <module path="/usr/lib/libunwind.so.8.0.1" address="7f280e8f9000" size="00002000" version="8.0.1"/>
    <module path="/usr/lib/libunwind.so.8.0.1" address="7f280e904000" size="00003000" version="8.0.1"/>
    <module path="/usr/lib/libunwind.so.8.0.1" address="7f280e908000" size="00001000" version="8.0.1"/>
    <module path="/usr/lib/libgpg-error.so.0.28.0" address="7f280e913000" size="00004000" version="0.28.0"/>
    <module path="/usr/lib/libgpg-error.so.0.28.0" address="7f280e929000" size="0000a000" version="0.28.0"/>
    <module path="/usr/lib/libgpg-error.so.0.28.0" address="7f280e934000" size="00001000" version="0.28.0"/>
    <module path="/usr/lib/libbrotlidec.so.1.0.7" address="7f280e937000" size="00001000" version="1.0.7"/>
    <module path="/usr/lib/libbrotlidec.so.1.0.7" address="7f280e93f000" size="00003000" version="1.0.7"/>
    <module path="/usr/lib/libbrotlidec.so.1.0.7" address="7f280e943000" size="00001000" version="1.0.7"/>
    <module path="/usr/lib/libwoff2common.so.1.0.2" address="7f280e945000" size="00002000" version="1.0.2"/>
    <module path="/usr/lib/libwoff2common.so.1.0.2" address="7f280eb46000" size="00001000" version="1.0.2"/>
    <module path="/usr/lib/libicudata.so.65.1" address="7f280eb48000" size="01ab0000" version="65.1"/>
    <module path="/usr/lib/libGLX.so.0.0.0" address="7f28105f9000" size="00003000" version="0.0.0"/>
    <module path="/usr/lib/libGLX.so.0.0.0" address="7f2810616000" size="00003000" version="0.0.0"/>
    <module path="/usr/lib/libGLX.so.0.0.0" address="7f281061a000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libGLdispatch.so.0.0.0" address="7f281062c000" size="00040000" version="0.0.0"/>
    <module path="/usr/lib/libGLdispatch.so.0.0.0" address="7f28106aa000" size="00013000" version="0.0.0"/>
    <module path="/usr/lib/libGLdispatch.so.0.0.0" address="7f28106be000" size="0001c000" version="0.0.0"/>
    <module path="/usr/lib/libblkid.so.1.1.0" address="7f28106e5000" size="00009000" version="1.1.0"/>
    <module path="/usr/lib/libblkid.so.1.1.0" address="7f2810720000" size="00010000" version="1.1.0"/>
    <module path="/usr/lib/libblkid.so.1.1.0" address="7f2810731000" size="00004000" version="1.1.0"/>
    <module path="/usr/lib/libatspi.so.0.0.1" address="7f2810736000" size="00010000" version="0.0.1"/>
    <module path="/usr/lib/libatspi.so.0.0.1" address="7f281075b000" size="0000d000" version="0.0.1"/>
    <module path="/usr/lib/libatspi.so.0.0.1" address="7f281076c000" size="00001000" version="0.0.1"/>
    <module path="/usr/lib/libdbus-1.so.3.19.11" address="7f281077b000" size="00028000" version="3.19.11"/>
    <module path="/usr/lib/libdbus-1.so.3.19.11" address="7f28107b4000" size="00002000" version="3.19.11"/>
    <module path="/usr/lib/libbz2.so.1.0.8" address="7f28107b7000" size="00002000" version="1.0.8"/>
    <module path="/usr/lib/libbz2.so.1.0.8" address="7f28107c6000" size="00002000" version="1.0.8"/>
    <module path="/usr/lib/libbz2.so.1.0.8" address="7f28107c9000" size="00001000" version="1.0.8"/>
    <module path="/usr/lib/libgraphite2.so.3.2.1" address="7f28107cc000" size="00003000" version="3.2.1"/>
    <module path="/usr/lib/libgraphite2.so.3.2.1" address="7f28107e9000" size="00005000" version="3.2.1"/>
    <module path="/usr/lib/libgraphite2.so.3.2.1" address="7f28107f0000" size="00001000" version="3.2.1"/>
    <module path="/usr/lib/liblzma.so.5.2.5" address="7f28107f4000" size="00017000" version="5.2.5"/>
    <module path="/usr/lib/liblzma.so.5.2.5" address="7f2810816000" size="00001000" version="5.2.5"/>
    <module path="/usr/lib/liblzma.so.5.2.5" address="7f2810818000" size="00001000" version="5.2.5"/>
    <module path="/usr/lib/libzstd.so.1.4.4" address="7f281081e000" size="00092000" version="1.4.4"/>
    <module path="/usr/lib/libzstd.so.1.4.4" address="7f28108c1000" size="00001000" version="1.4.4"/>
    <module path="/usr/lib/libuuid.so.1.3.0" address="7f28108c3000" size="00002000" version="1.3.0"/>
    <module path="/usr/lib/libuuid.so.1.3.0" address="7f28108c9000" size="00001000" version="1.3.0"/>
    <module path="/usr/lib/libuuid.so.1.3.0" address="7f28108cb000" size="00001000" version="1.3.0"/>
    <module path="/usr/lib/libICE.so.6.3.0" address="7f28108d1000" size="0000e000" version="6.3.0"/>
    <module path="/usr/lib/libICE.so.6.3.0" address="7f28108e4000" size="00001000" version="6.3.0"/>
    <module path="/usr/lib/libXrender.so.1.3.0" address="7f28108eb000" size="00002000" version="1.3.0"/>
    <module path="/usr/lib/libXrender.so.1.3.0" address="7f28108f4000" size="00002000" version="1.3.0"/>
    <module path="/usr/lib/libXrender.so.1.3.0" address="7f28108f7000" size="00001000" version="1.3.0"/>
    <module path="/usr/lib/libxcb-render.so.0.0.0" address="7f28108fe000" size="00005000" version="0.0.0"/>
    <module path="/usr/lib/libxcb-render.so.0.0.0" address="7f2810905000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libxcb-render.so.0.0.0" address="7f2810907000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libxcb.so.1.1.0" address="7f2810914000" size="00013000" version="1.1.0"/>
    <module path="/usr/lib/libxcb.so.1.1.0" address="7f2810930000" size="00001000" version="1.1.0"/>
    <module path="/usr/lib/libxcb-shm.so.0.0.0" address="7f2810932000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libxcb-shm.so.0.0.0" address="7f2810934000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libxcb-shm.so.0.0.0" address="7f2810936000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libpixman-1.so.0.38.4" address="7f2810942000" size="00086000" version="0.38.4"/>
    <module path="/usr/lib/libpixman-1.so.0.38.4" address="7f28109d8000" size="00008000" version="0.38.4"/>
    <module path="/usr/lib/libthai.so.0.3.1" address="7f28109e1000" size="00002000" version="0.3.1"/>
    <module path="/usr/lib/libthai.so.0.3.1" address="7f28109e7000" size="00003000" version="0.3.1"/>
    <module path="/usr/lib/libthai.so.0.3.1" address="7f28109eb000" size="00001000" version="0.3.1"/>
    <module path="/usr/lib/libwayland-server.so.0.1.0" address="7f28109ee000" size="00007000" version="0.1.0"/>
    <module path="/usr/lib/libwayland-server.so.0.1.0" address="7f28109fc000" size="00004000" version="0.1.0"/>
    <module path="/usr/lib/libwayland-server.so.0.1.0" address="7f2810a01000" size="00002000" version="0.1.0"/>
    <module path="/usr/lib/libhyphen.so.0.3.0" address="7f2810a04000" size="00005000" version="0.3.0"/>
    <module path="/usr/lib/libhyphen.so.0.3.0" address="7f2810c08000" size="00001000" version="0.3.0"/>
    <module path="/usr/lib/libtasn1.so.6.6.0" address="7f2810c0a000" size="00003000" version="6.6.0"/>
    <module path="/usr/lib/libtasn1.so.6.6.0" address="7f2810c19000" size="00004000" version="6.6.0"/>
    <module path="/usr/lib/libtasn1.so.6.6.0" address="7f2810c1e000" size="00001000" version="6.6.0"/>
    <module path="/usr/lib/libsecret-1.so.0.0.0" address="7f2810c20000" size="00014000" version="0.0.0"/>
    <module path="/usr/lib/libsecret-1.so.0.0.0" address="7f2810c65000" size="00017000" version="0.0.0"/>
    <module path="/usr/lib/libsecret-1.so.0.0.0" address="7f2810c7d000" size="00004000" version="0.0.0"/>
    <module path="/usr/lib/libseccomp.so.2.4.2" address="7f2810c82000" size="00025000" version="2.4.2"/>
    <module path="/usr/lib/libseccomp.so.2.4.2" address="7f2810cb1000" size="00004000" version="2.4.2"/>
    <module path="/usr/lib/libseccomp.so.2.4.2" address="7f2810cce000" size="00001000" version="2.4.2"/>
    <module path="/usr/lib/libenchant-2.so.2.2.8" address="7f2810cd1000" size="00003000" version="2.2.8"/>
    <module path="/usr/lib/libenchant-2.so.2.2.8" address="7f2810cd9000" size="00002000" version="2.2.8"/>
    <module path="/usr/lib/libenchant-2.so.2.2.8" address="7f2810cdc000" size="00001000" version="2.2.8"/>
    <module path="/usr/lib/libsoup-2.4.so.1.9.0" address="7f2810cde000" size="0001d000" version="1.9.0"/>
    <module path="/usr/lib/libsoup-2.4.so.1.9.0" address="7f2810d4d000" size="00026000" version="1.9.0"/>
    <module path="/usr/lib/libsoup-2.4.so.1.9.0" address="7f2810d78000" size="00001000" version="1.9.0"/>
    <module path="/usr/lib/libwebpdemux.so.2.0.6" address="7f2810d7a000" size="00002000" version="2.0.6"/>
    <module path="/usr/lib/libwebpdemux.so.2.0.6" address="7f2810d7d000" size="00001000" version="2.0.6"/>
    <module path="/usr/lib/libwebp.so.7.1.0" address="7f2810d7f000" size="00003000" version="7.1.0"/>
    <module path="/usr/lib/libwebp.so.7.1.0" address="7f2810dd8000" size="00013000" version="7.1.0"/>
    <module path="/usr/lib/libwebp.so.7.1.0" address="7f2810dec000" size="00001000" version="7.1.0"/>
    <module path="/usr/lib/libopenjp2.so.2.3.1" address="7f2810def000" size="00008000" version="2.3.1"/>
    <module path="/usr/lib/libopenjp2.so.2.3.1" address="7f2810e3c000" size="0000d000" version="2.3.1"/>
    <module path="/usr/lib/libopenjp2.so.2.3.1" address="7f2810e4b000" size="00001000" version="2.3.1"/>
    <module path="/usr/lib/libgstfft-1.0.so.0.1602.0" address="7f2810e4d000" size="00006000" version="0.1602.0"/>
    <module path="/usr/lib/libgstfft-1.0.so.0.1602.0" address="7f2810e54000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgstgl-1.0.so.0.1602.0" address="7f2810e58000" size="00015000" version="0.1602.0"/>
    <module path="/usr/lib/libgstgl-1.0.so.0.1602.0" address="7f2810ea0000" size="0001d000" version="0.1602.0"/>
    <module path="/usr/lib/libgstgl-1.0.so.0.1602.0" address="7f2810ebe000" size="00005000" version="0.1602.0"/>
    <module path="/usr/lib/libgstvideo-1.0.so.0.1602.0" address="7f2810ec4000" size="00016000" version="0.1602.0"/>
    <module path="/usr/lib/libgstvideo-1.0.so.0.1602.0" address="7f2810f34000" size="00023000" version="0.1602.0"/>
    <module path="/usr/lib/libgstvideo-1.0.so.0.1602.0" address="7f2810f58000" size="0000c000" version="0.1602.0"/>
    <module path="/usr/lib/libgsttag-1.0.so.0.1602.0" address="7f2810f65000" size="00009000" version="0.1602.0"/>
    <module path="/usr/lib/libgsttag-1.0.so.0.1602.0" address="7f2810f8b000" size="00010000" version="0.1602.0"/>
    <module path="/usr/lib/libgsttag-1.0.so.0.1602.0" address="7f2810f9c000" size="00002000" version="0.1602.0"/>
    <module path="/usr/lib/libgstaudio-1.0.so.0.1602.0" address="7f2810f9f000" size="0000f000" version="0.1602.0"/>
    <module path="/usr/lib/libgstaudio-1.0.so.0.1602.0" address="7f2810ff1000" size="0001b000" version="0.1602.0"/>
    <module path="/usr/lib/libgstaudio-1.0.so.0.1602.0" address="7f2811010000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgstpbutils-1.0.so.0.1602.0" address="7f281101f000" size="00017000" version="0.1602.0"/>
    <module path="/usr/lib/libgstpbutils-1.0.so.0.1602.0" address="7f2811042000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgstpbutils-1.0.so.0.1602.0" address="7f2811046000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgstreamer-1.0.so.0.1602.0" address="7f2811074000" size="0008f000" version="0.1602.0"/>
    <module path="/usr/lib/libgstreamer-1.0.so.0.1602.0" address="7f281114b000" size="00007000" version="0.1602.0"/>
    <module path="/usr/lib/libgstbase-1.0.so.0.1602.0" address="7f2811157000" size="0000e000" version="0.1602.0"/>
    <module path="/usr/lib/libgstbase-1.0.so.0.1602.0" address="7f28111aa000" size="0001a000" version="0.1602.0"/>
    <module path="/usr/lib/libgstbase-1.0.so.0.1602.0" address="7f28111c6000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgstapp-1.0.so.0.1602.0" address="7f28111cb000" size="00006000" version="0.1602.0"/>
    <module path="/usr/lib/libgstapp-1.0.so.0.1602.0" address="7f28111d5000" size="00001000" version="0.1602.0"/>
    <module path="/usr/lib/libgcrypt.so.20.2.5" address="7f28111d7000" size="0000c000" version="20.2.5"/>
    <module path="/usr/lib/libgcrypt.so.20.2.5" address="7f28112b1000" size="0003c000" version="20.2.5"/>
    <module path="/usr/lib/libgcrypt.so.20.2.5" address="7f28112ee000" size="00002000" version="20.2.5"/>
    <module path="/usr/lib/libharfbuzz-icu.so.0.20600.5" address="7f28112f5000" size="00001000" version="0.20600.5"/>
    <module path="/usr/lib/libharfbuzz-icu.so.0.20600.5" address="7f28112f7000" size="00001000" version="0.20600.5"/>
    <module path="/usr/lib/libharfbuzz-icu.so.0.20600.5" address="7f28112f9000" size="00001000" version="0.20600.5"/>
    <module path="/usr/lib/libwoff2dec.so.1.0.2" address="7f2811303000" size="00200000" version="1.0.2"/>
    <module path="/usr/lib/libwoff2dec.so.1.0.2" address="7f2811504000" size="00001000" version="1.0.2"/>
    <module path="/usr/lib/libicuuc.so.65.1" address="7f2811569000" size="000e3000" version="65.1"/>
    <module path="/usr/lib/libicuuc.so.65.1" address="7f28116d1000" size="00001000" version="65.1"/>
    <module path="/usr/lib/libicuuc.so.65.1" address="7f28116e4000" size="00001000" version="65.1"/>
    <module path="/usr/lib/libicui18n.so.65.1" address="7f28116e9000" size="000e4000" version="65.1"/>
    <module path="/usr/lib/libicui18n.so.65.1" address="7f2811943000" size="00086000" version="65.1"/>
    <module path="/usr/lib/libicui18n.so.65.1" address="7f28119ca000" size="00010000" version="65.1"/>
    <module path="/usr/lib/libjavascriptcoregtk-4.0.so.18.16.4" address="7f28119dc000" size="016f9000" version="18.16.4"/>
    <module path="/usr/lib/libjavascriptcoregtk-4.0.so.18.16.4" address="7f28130d8000" size="00068000" version="18.16.4"/>
    <module path="/usr/lib/libxslt.so.1.1.34" address="7f2813155000" size="0000a000" version="1.1.34"/>
    <module path="/usr/lib/libxslt.so.1.1.34" address="7f2813185000" size="0000e000" version="1.1.34"/>
    <module path="/usr/lib/libxslt.so.1.1.34" address="7f2813194000" size="00001000" version="1.1.34"/>
    <module path="/usr/lib/libxml2.so.2.9.10" address="7f2813196000" size="0002e000" version="2.9.10"/>
    <module path="/usr/lib/libxml2.so.2.9.10" address="7f28132a6000" size="0004a000" version="2.9.10"/>
    <module path="/usr/lib/libxml2.so.2.9.10" address="7f28132f9000" size="00001000" version="2.9.10"/>
    <module path="/usr/lib/libsqlite3.so.0.8.6" address="7f28132fc000" size="00021000" version="0.8.6"/>
    <module path="/usr/lib/libsqlite3.so.0.8.6" address="7f28133ed000" size="00037000" version="0.8.6"/>
    <module path="/usr/lib/libsqlite3.so.0.8.6" address="7f281342a000" size="00003000" version="0.8.6"/>
    <module path="/usr/lib/libEGL.so.1.1.0" address="7f2813430000" size="00008000" version="1.1.0"/>
    <module path="/usr/lib/libEGL.so.1.1.0" address="7f281343c000" size="00001000" version="1.1.0"/>
    <module path="/usr/lib/libGL.so.1.7.0" address="7f2813440000" size="00042000" version="1.7.0"/>
    <module path="/usr/lib/libGL.so.1.7.0" address="7f28134a1000" size="00015000" version="1.7.0"/>
    <module path="/usr/lib/libGL.so.1.7.0" address="7f28134c4000" size="00001000" version="1.7.0"/>
    <module path="/usr/lib/libWPEBackend-fdo-1.0.so.1.6.1" address="7f28134c6000" size="00004000" version="1.6.1"/>
    <module path="/usr/lib/libWPEBackend-fdo-1.0.so.1.6.1" address="7f28134cf000" size="00003000" version="1.6.1"/>
    <module path="/usr/lib/libWPEBackend-fdo-1.0.so.1.6.1" address="7f28134d3000" size="00001000" version="1.6.1"/>
    <module path="/usr/lib/libwpe-1.0.so.1.3.2" address="7f28134d5000" size="00003000" version="1.3.2"/>
    <module path="/usr/lib/libwpe-1.0.so.1.3.2" address="7f28134da000" size="00003000" version="1.3.2"/>
    <module path="/usr/lib/libwpe-1.0.so.1.3.2" address="7f28134de000" size="00001000" version="1.3.2"/>
    <module path="/usr/lib/libpcre.so.1.2.12" address="7f28134e1000" size="00050000" version="1.2.12"/>
    <module path="/usr/lib/libpcre.so.1.2.12" address="7f281354f000" size="00001000" version="1.2.12"/>
    <module path="/usr/lib/libresolv-2.31.so" address="7f2813551000" size="00004000" version="2.31"/>
    <module path="/usr/lib/libresolv-2.31.so" address="7f2813562000" size="00003000" version="2.31"/>
    <module path="/usr/lib/libresolv-2.31.so" address="7f2813566000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libmount.so.1.1.0" address="7f281356a000" size="0000c000" version="1.1.0"/>
    <module path="/usr/lib/libmount.so.1.1.0" address="7f28135b1000" size="00012000" version="1.1.0"/>
    <module path="/usr/lib/libmount.so.1.1.0" address="7f28135c4000" size="00002000" version="1.1.0"/>
    <module path="/usr/lib/libffi.so.7.1.0" address="7f28135c9000" size="00002000" version="7.1.0"/>
    <module path="/usr/lib/libffi.so.7.1.0" address="7f28135d1000" size="00001000" version="7.1.0"/>
    <module path="/usr/lib/libffi.so.7.1.0" address="7f28135d3000" size="00001000" version="7.1.0"/>
    <module path="/usr/lib/libXinerama.so.1.0.0" address="7f28135d5000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXinerama.so.1.0.0" address="7f28135d7000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXinerama.so.1.0.0" address="7f28135d9000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXrandr.so.2.2.0" address="7f28135dc000" size="00007000" version="2.2.0"/>
    <module path="/usr/lib/libXrandr.so.2.2.0" address="7f28135e5000" size="00001000" version="2.2.0"/>
    <module path="/usr/lib/libXcomposite.so.1.0.0" address="7f28135e7000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXcomposite.so.1.0.0" address="7f28135e9000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXcomposite.so.1.0.0" address="7f28135eb000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXdamage.so.1.1.0" address="7f28135ed000" size="00001000" version="1.1.0"/>
    <module path="/usr/lib/libXdamage.so.1.1.0" address="7f28135ef000" size="00001000" version="1.1.0"/>
    <module path="/usr/lib/libXcursor.so.1.0.2" address="7f28135f1000" size="00003000" version="1.0.2"/>
    <module path="/usr/lib/libXcursor.so.1.0.2" address="7f28135f9000" size="00002000" version="1.0.2"/>
    <module path="/usr/lib/libXcursor.so.1.0.2" address="7f28135fc000" size="00001000" version="1.0.2"/>
    <module path="/usr/lib/libXext.so.6.4.0" address="7f28135ff000" size="00004000" version="6.4.0"/>
    <module path="/usr/lib/libXext.so.6.4.0" address="7f281360e000" size="00004000" version="6.4.0"/>
    <module path="/usr/lib/libXext.so.6.4.0" address="7f2813613000" size="00001000" version="6.4.0"/>
    <module path="/usr/lib/libwayland-egl.so.1.0.0" address="7f2813615000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libwayland-egl.so.1.0.0" address="7f2813617000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libwayland-cursor.so.0.0.0" address="7f2813619000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libwayland-cursor.so.0.0.0" address="7f281361c000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/libwayland-cursor.so.0.0.0" address="7f281361e000" size="00004000" version="0.0.0"/>
    <module path="/usr/lib/libwayland-client.so.0.3.0" address="7f2813628000" size="00005000" version="0.3.0"/>
    <module path="/usr/lib/libwayland-client.so.0.3.0" address="7f2813630000" size="00002000" version="0.3.0"/>
    <module path="/usr/lib/libxkbcommon.so.0.0.0" address="7f2813633000" size="00005000" version="0.0.0"/>
    <module path="/usr/lib/libxkbcommon.so.0.0.0" address="7f2813653000" size="0001e000" version="0.0.0"/>
    <module path="/usr/lib/libxkbcommon.so.0.0.0" address="7f2813673000" size="00001000" version="0.0.0"/>
    <module path="/usr/lib/librt-2.31.so" address="7f2813677000" size="00004000" version="2.31"/>
    <module path="/usr/lib/librt-2.31.so" address="7f281367c000" size="00001000" version="2.31"/>
    <module path="/usr/lib/librt-2.31.so" address="7f281367e000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libXfixes.so.3.1.0" address="7f2813681000" size="00002000" version="3.1.0"/>
    <module path="/usr/lib/libXfixes.so.3.1.0" address="7f2813686000" size="00001000" version="3.1.0"/>
    <module path="/usr/lib/libXfixes.so.3.1.0" address="7f2813688000" size="00001000" version="3.1.0"/>
    <module path="/usr/lib/libatk-bridge-2.0.so.0.0.0" address="7f281368a000" size="0000c000" version="0.0.0"/>
    <module path="/usr/lib/libatk-bridge-2.0.so.0.0.0" address="7f28136ac000" size="0000e000" version="0.0.0"/>
    <module path="/usr/lib/libatk-bridge-2.0.so.0.0.0" address="7f28136bb000" size="00002000" version="0.0.0"/>
    <module path="/usr/lib/libXi.so.6.1.0" address="7f28136bf000" size="00003000" version="6.1.0"/>
    <module path="/usr/lib/libXi.so.6.1.0" address="7f28136cd000" size="00003000" version="6.1.0"/>
    <module path="/usr/lib/libXi.so.6.1.0" address="7f28136d1000" size="00001000" version="6.1.0"/>
    <module path="/usr/lib/libepoxy.so.0.0.0" address="7f2813730000" size="00063000" version="0.0.0"/>
    <module path="/usr/lib/libepoxy.so.0.0.0" address="7f28137ee000" size="00008000" version="0.0.0"/>
    <module path="/usr/lib/libatk-1.0.so.0.23609.1" address="7f28137fd000" size="0000b000" version="0.23609.1"/>
    <module path="/usr/lib/libatk-1.0.so.0.23609.1" address="7f2813816000" size="0000c000" version="0.23609.1"/>
    <module path="/usr/lib/libatk-1.0.so.0.23609.1" address="7f2813825000" size="00001000" version="0.23609.1"/>
    <module path="/usr/lib/libcairo-gobject.so.2.11703.0" address="7f281382a000" size="00002000" version="2.11703.0"/>
    <module path="/usr/lib/libcairo-gobject.so.2.11703.0" address="7f281382e000" size="00001000" version="2.11703.0"/>
    <module path="/usr/lib/libcairo-gobject.so.2.11703.0" address="7f2813831000" size="00001000" version="2.11703.0"/>
    <module path="/usr/lib/libfribidi.so.0.4.0" address="7f2813834000" size="00005000" version="0.4.0"/>
    <module path="/usr/lib/libfribidi.so.0.4.0" address="7f281384f000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libfreetype.so.6.17.1" address="7f2813853000" size="0000d000" version="6.17.1"/>
    <module path="/usr/lib/libfreetype.so.6.17.1" address="7f28138e1000" size="00037000" version="6.17.1"/>
    <module path="/usr/lib/libfreetype.so.6.17.1" address="7f2813919000" size="00007000" version="6.17.1"/>
    <module path="/usr/lib/libfontconfig.so.1.12.0" address="7f2813921000" size="00008000" version="1.12.0"/>
    <module path="/usr/lib/libfontconfig.so.1.12.0" address="7f281394d000" size="00018000" version="1.12.0"/>
    <module path="/usr/lib/libfontconfig.so.1.12.0" address="7f2813966000" size="00002000" version="1.12.0"/>
    <module path="/usr/lib/libpangoft2-1.0.so.0.4400.7" address="7f2813969000" size="00007000" version="0.4400.7"/>
    <module path="/usr/lib/libpangoft2-1.0.so.0.4400.7" address="7f2813979000" size="00004000" version="0.4400.7"/>
    <module path="/usr/lib/libpangoft2-1.0.so.0.4400.7" address="7f281397e000" size="00001000" version="0.4400.7"/>
    <module path="/usr/lib/libharfbuzz.so.0.20600.5" address="7f2813980000" size="0000a000" version="0.20600.5"/>
    <module path="/usr/lib/libharfbuzz.so.0.20600.5" address="7f2813a4e000" size="00033000" version="0.20600.5"/>
    <module path="/usr/lib/libharfbuzz.so.0.20600.5" address="7f2813a82000" size="00001000" version="0.20600.5"/>
    <module path="/usr/lib/libgmodule-2.0.so.0.6400.2" address="7f2813a84000" size="00001000" version="0.6400.2"/>
    <module path="/usr/lib/libgmodule-2.0.so.0.6400.2" address="7f2813a86000" size="00001000" version="0.6400.2"/>
    <module path="/usr/lib/libgmodule-2.0.so.0.6400.2" address="7f2813a88000" size="00001000" version="0.6400.2"/>
    <module path="/usr/lib/libz.so.1.2.11" address="7f2813a8b000" size="00003000" version="1.2.11"/>
    <module path="/usr/lib/libz.so.1.2.11" address="7f2813a9c000" size="00006000" version="1.2.11"/>
    <module path="/usr/lib/libz.so.1.2.11" address="7f2813aa3000" size="00001000" version="1.2.11"/>
    <module path="/usr/lib/libexpat.so.1.6.11" address="7f2813aa5000" size="00004000" version="1.6.11"/>
    <module path="/usr/lib/libexpat.so.1.6.11" address="7f2813ac7000" size="0000a000" version="1.6.11"/>
    <module path="/usr/lib/libexpat.so.1.6.11" address="7f2813ad2000" size="00002000" version="1.6.11"/>
    <module path="/usr/lib/libtiff.so.5.5.0" address="7f2813ad5000" size="00009000" version="5.5.0"/>
    <module path="/usr/lib/libtiff.so.5.5.0" address="7f2813b2c000" size="0002f000" version="5.5.0"/>
    <module path="/usr/lib/libtiff.so.5.5.0" address="7f2813b5c000" size="00004000" version="5.5.0"/>
    <module path="/usr/lib/libjpeg.so.8.2.2" address="7f2813b64000" size="00004000" version="8.2.2"/>
    <module path="/usr/lib/libjpeg.so.8.2.2" address="7f2813bbe000" size="0003a000" version="8.2.2"/>
    <module path="/usr/lib/libjpeg.so.8.2.2" address="7f2813bf9000" size="00001000" version="8.2.2"/>
    <module path="/usr/lib/libpng16.so.16.37.0" address="7f2813bfb000" size="00006000" version="16.37.0"/>
    <module path="/usr/lib/libpng16.so.16.37.0" address="7f2813c25000" size="0000c000" version="16.37.0"/>
    <module path="/usr/lib/libpng16.so.16.37.0" address="7f2813c32000" size="00001000" version="16.37.0"/>
    <module path="/usr/lib/libSM.so.6.0.1" address="7f2813c35000" size="00005000" version="6.0.1"/>
    <module path="/usr/lib/libSM.so.6.0.1" address="7f2813c3c000" size="00001000" version="6.0.1"/>
    <module path="/usr/lib/libXxf86vm.so.1.0.0" address="7f2813c40000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXxf86vm.so.1.0.0" address="7f2813c44000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libXxf86vm.so.1.0.0" address="7f2813c46000" size="00001000" version="1.0.0"/>
    <module path="/usr/lib/libpangocairo-1.0.so.0.4400.7" address="7f2813c4c000" size="00006000" version="0.4400.7"/>
    <module path="/usr/lib/libpangocairo-1.0.so.0.4400.7" address="7f2813c54000" size="00001000" version="0.4400.7"/>
    <module path="/usr/lib/libpangocairo-1.0.so.0.4400.7" address="7f2813c56000" size="00001000" version="0.4400.7"/>
    <module path="/usr/lib/libnotify.so.4.0.0" address="7f2813c5a000" size="00003000" version="4.0.0"/>
    <module path="/usr/lib/libnotify.so.4.0.0" address="7f2813c5f000" size="00001000" version="4.0.0"/>
    <module path="/usr/lib/libX11.so.6.3.0" address="7f2813c61000" size="0001c000" version="6.3.0"/>
    <module path="/usr/lib/libX11.so.6.3.0" address="7f2813d06000" size="00094000" version="6.3.0"/>
    <module path="/usr/lib/libX11.so.6.3.0" address="7f2813d9d000" size="00004000" version="6.3.0"/>
    <module path="/usr/lib/libgdk_pixbuf-2.0.so.0.4000.0" address="7f2813da7000" size="00015000" version="0.4000.0"/>
    <module path="/usr/lib/libgdk_pixbuf-2.0.so.0.4000.0" address="7f2813dc4000" size="00001000" version="0.4000.0"/>
    <module path="/usr/lib/libgdk_pixbuf-2.0.so.0.4000.0" address="7f2813dc6000" size="00001000" version="0.4000.0"/>
    <module path="/usr/lib/libcairo.so.2.11703.0" address="7f2813dd9000" size="000cf000" version="2.11703.0"/>
    <module path="/usr/lib/libcairo.so.2.11703.0" address="7f2813ee4000" size="00001000" version="2.11703.0"/>
    <module path="/usr/lib/libcairo.so.2.11703.0" address="7f2813ee9000" size="00001000" version="2.11703.0"/>
    <module path="/usr/lib/libpango-1.0.so.0.4400.7" address="7f2813eed000" size="0000f000" version="0.4400.7"/>
    <module path="/usr/lib/libpango-1.0.so.0.4400.7" address="7f2813f20000" size="00017000" version="0.4400.7"/>
    <module path="/usr/lib/libpango-1.0.so.0.4400.7" address="7f2813f3a000" size="00001000" version="0.4400.7"/>
    <module path="/usr/lib/libwebkit2gtk-4.0.so.37.44.3" address="7f2817124000" size="00227000" version="37.44.3"/>
    <module path="/usr/lib/libglib-2.0.so.0.6400.2" address="7f28173b5000" size="0001c000" version="0.6400.2"/>
    <module path="/usr/lib/libglib-2.0.so.0.6400.2" address="7f2817454000" size="00085000" version="0.6400.2"/>
    <module path="/usr/lib/libglib-2.0.so.0.6400.2" address="7f28174da000" size="00001000" version="0.6400.2"/>
    <module path="/usr/lib/libgio-2.0.so.0.6400.2" address="7f28174dd000" size="00036000" version="0.6400.2"/>
    <module path="/usr/lib/libgio-2.0.so.0.6400.2" address="7f2817608000" size="0007d000" version="0.6400.2"/>
    <module path="/usr/lib/libgio-2.0.so.0.6400.2" address="7f2817686000" size="00007000" version="0.6400.2"/>
    <module path="/usr/lib/libgobject-2.0.so.0.6400.2" address="7f2817690000" size="0000e000" version="0.6400.2"/>
    <module path="/usr/lib/libgobject-2.0.so.0.6400.2" address="7f28176d3000" size="00018000" version="0.6400.2"/>
    <module path="/usr/lib/libgobject-2.0.so.0.6400.2" address="7f28176ee000" size="00001000" version="0.6400.2"/>
    <module path="/usr/lib/libgdk-3.so.0.2410.7" address="7f28176f1000" size="0002a000" version="0.2410.7"/>
    <module path="/usr/lib/libgdk-3.so.0.2410.7" address="7f2817794000" size="0004c000" version="0.2410.7"/>
    <module path="/usr/lib/libgdk-3.so.0.2410.7" address="7f28177e1000" size="00008000" version="0.2410.7"/>
    <module path="/usr/lib/libgtk-3.so.0.2410.7" address="7f28177eb000" size="00082000" version="0.2410.7"/>
    <module path="/usr/lib/libgtk-3.so.0.2410.7" address="7f2817bc4000" size="0038c000" version="0.2410.7"/>
    <module path="/usr/lib/libgtk-3.so.0.2410.7" address="7f2817f51000" size="00010000" version="0.2410.7"/>
    <module path="/usr/lib/libc-2.31.so" address="7f2817f68000" size="00025000" version="2.31"/>
    <module path="/usr/lib/libc-2.31.so" address="7f28180d9000" size="0004b000" version="2.31"/>
    <module path="/usr/lib/libc-2.31.so" address="7f2818127000" size="00003000" version="2.31"/>
    <module path="/usr/lib/libpthread-2.31.so" address="7f281812e000" size="00007000" version="2.31"/>
    <module path="/usr/lib/libpthread-2.31.so" address="7f2818145000" size="00005000" version="2.31"/>
    <module path="/usr/lib/libpthread-2.31.so" address="7f281814b000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libgcc_s.so.1" address="7f2818150000" size="00003000" version="1"/>
    <module path="/usr/lib/libgcc_s.so.1" address="7f2818164000" size="00004000" version="1"/>
    <module path="/usr/lib/libgcc_s.so.1" address="7f2818169000" size="00001000" version="1"/>
    <module path="/usr/lib/libm-2.31.so" address="7f2818179000" size="0009c000" version="2.31"/>
    <module path="/usr/lib/libm-2.31.so" address="7f28182ae000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libstdc++.so.6.0.28" address="7f28182b2000" size="00096000" version="6.0.28"/>
    <module path="/usr/lib/libstdc++.so.6.0.28" address="7f2818441000" size="00049000" version="6.0.28"/>
    <module path="/usr/lib/libstdc++.so.6.0.28" address="7f2818497000" size="00001000" version="6.0.28"/>
    <module path="/usr/lib/libdl-2.31.so" address="7f281849b000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libdl-2.31.so" address="7f281849d000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libdl-2.31.so" address="7f281849f000" size="00001000" version="2.31"/>
    <module path="/usr/lib/libwx_baseu-3.0.so.0.4.0" address="7f2818501000" size="001a4000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu-3.0.so.0.4.0" address="7f2818728000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu-3.0.so.0.4.0" address="7f2818737000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu_net-3.0.so.0.4.0" address="7f2818743000" size="00011000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu_net-3.0.so.0.4.0" address="7f281877a000" size="0000c000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu_net-3.0.so.0.4.0" address="7f2818787000" size="00003000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu_xml-3.0.so.0.4.0" address="7f281878b000" size="00005000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu_xml-3.0.so.0.4.0" address="7f2818798000" size="00003000" version="0.4.0"/>
    <module path="/usr/lib/libwx_baseu_xml-3.0.so.0.4.0" address="7f281879c000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_core-3.0.so.0.4.0" address="7f281879e000" size="00209000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_core-3.0.so.0.4.0" address="7f2818c63000" size="000ec000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_core-3.0.so.0.4.0" address="7f2818d50000" size="00078000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_adv-3.0.so.0.4.0" address="7f2818dd7000" size="000a8000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_adv-3.0.so.0.4.0" address="7f2818f47000" size="00042000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_adv-3.0.so.0.4.0" address="7f2818fac000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_qa-3.0.so.0.4.0" address="7f2818fb0000" size="0000e000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_qa-3.0.so.0.4.0" address="7f2818fd7000" size="00006000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_qa-3.0.so.0.4.0" address="7f2818fe0000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_html-3.0.so.0.4.0" address="7f2819020000" size="00067000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_html-3.0.so.0.4.0" address="7f28190a6000" size="00001000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_html-3.0.so.0.4.0" address="7f28190b3000" size="00002000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_webview-3.0.so.0.4.0" address="7f28190b6000" size="0000d000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_webview-3.0.so.0.4.0" address="7f28190d0000" size="00004000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_webview-3.0.so.0.4.0" address="7f28190d5000" size="00002000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_stc-3.0.so.0.4.0" address="7f28190d8000" size="0002b000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_stc-3.0.so.0.4.0" address="7f28192e0000" size="00034000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_stc-3.0.so.0.4.0" address="7f2819315000" size="00007000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_aui-3.0.so.0.4.0" address="7f281931f000" size="00030000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_aui-3.0.so.0.4.0" address="7f2819393000" size="00016000" version="0.4.0"/>
    <module path="/usr/lib/libwx_gtk3u_aui-3.0.so.0.4.0" address="7f28193aa000" size="00009000" version="0.4.0"/>
    <module path="/home/feimosi/.local/share/mime/mime.cache" address="7f28193b7000" size="00001000"/>
    <module path="/usr/lib/gtk-3.0/modules/libcanberra-gtk3-module.so" address="7f28193ba000" size="00003000" version="module"/>
    <module path="/usr/lib/gtk-3.0/modules/libcanberra-gtk3-module.so" address="7f28193be000" size="00001000" version="module"/>
    <module path="/usr/lib/gio/modules/libgvfsdbus.so" address="7f28193c0000" size="0000a000"/>
    <module path="/usr/lib/gio/modules/libgvfsdbus.so" address="7f28193e3000" size="00009000"/>
    <module path="/usr/lib/gio/modules/libgvfsdbus.so" address="7f28193ed000" size="00002000"/>
    <module path="/usr/lib/gconv/UTF-32.so" address="7f28193f0000" size="00001000" version="32"/>
    <module path="/usr/lib/gconv/UTF-32.so" address="7f28193f3000" size="00001000" version="32"/>
    <module path="/usr/lib/gconv/UTF-32.so" address="7f28193f5000" size="00001000" version="32"/>
    <module path="/usr/lib/ld-2.31.so" address="7f28193f8000" size="00020000" version="2.31"/>
    <module path="/var/cache/fontconfig/923e285e415b1073c8df160bee08820f-le64.cache-7" address="7f2819420000" size="00001000"/>
    <module path="/usr/lib/ld-2.31.so" address="7f2819422000" size="00001000" version="2.31"/>
    <module path="[stack]" address="7ffef9966000" size="00021000"/>
    <module path="[vdso]" address="7ffef99c1000" size="00002000"/>
  </modules>
  <stack>
    <frame level="0"/>
    <frame level="1"/>
    <frame level="2"/>
    <frame level="3" function="g_type_check_instance_is_a" offset="0000003c"/>
    <frame level="4" function="g_dbus_server_get_client_address" offset="00000028"/>
    <frame level="5"/>
    <frame level="6" function="g_closure_invoke" offset="000001aa"/>
    <frame level="7"/>
    <frame level="8" function="g_signal_emit_valist" offset="00000cd9"/>
    <frame level="9" function="g_signal_emit" offset="00000090"/>
    <frame level="10"/>
    <frame level="11"/>
    <frame level="12"/>
    <frame level="13"/>
    <frame level="14"/>
    <frame level="15"/>
    <frame level="16"/>
    <frame level="17" function="webkit_web_view_load_uri" offset="000001bd"/>
    <frame level="18" function="wxWebViewWebKit::Create(wxWindow*, int, wxString const&amp;, wxPoint const&amp;, wxSize const&amp;, long, wxString const&amp;)" offset="0000035c"/>
    <frame level="19" function="wxWebView::New(wxWindow*, int, wxString const&amp;, wxPoint const&amp;, wxSize const&amp;, wxString const&amp;, long, wxString const&amp;)" offset="00000145"/>
    <frame level="20"/>
    <frame level="21"/>
    <frame level="22"/>
    <frame level="23"/>
    <frame level="24"/>
    <frame level="25"/>
    <frame level="26" function="wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&amp;, wxEvtHandler*, wxEvent&amp;)" offset="0000006e"/>
    <frame level="27" function="wxEvtHandler::SearchDynamicEventTable(wxEvent&amp;)" offset="0000006b"/>
    <frame level="28" function="wxEvtHandler::TryHereOnly(wxEvent&amp;)" offset="00000021"/>
    <frame level="29" function="wxEvtHandler::ProcessEventLocally(wxEvent&amp;)" offset="00000034"/>
    <frame level="30" function="wxEvtHandler::ProcessEvent(wxEvent&amp;)" offset="00000082"/>
    <frame level="31" function="wxScrollHelperEvtHandler::ProcessEvent(wxEvent&amp;)" offset="0000001d"/>
    <frame level="32" function="wxGenericTreeCtrl::DoSelectItem(wxTreeItemId const&amp;, bool, bool)" offset="000001b2"/>
    <frame level="33" function="wxGenericTreeCtrl::OnMouse(wxMouseEvent&amp;)" offset="00000411"/>
    <frame level="34"/>
    <frame level="35" function="wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&amp;, wxEvtHandler*, wxEvent&amp;)" offset="0000006e"/>
    <frame level="36" function="wxEventHashTable::HandleEvent(wxEvent&amp;, wxEvtHandler*)" offset="00000094"/>
    <frame level="37" function="wxEvtHandler::TryHereOnly(wxEvent&amp;)" offset="0000004e"/>
    <frame level="38" function="wxEvtHandler::ProcessEventLocally(wxEvent&amp;)" offset="00000034"/>
    <frame level="39" function="wxEvtHandler::ProcessEvent(wxEvent&amp;)" offset="00000082"/>
    <frame level="40" function="wxScrollHelperEvtHandler::ProcessEvent(wxEvent&amp;)" offset="0000001d"/>
    <frame level="41" function="wxEvtHandler::SafelyProcessEvent(wxEvent&amp;)" offset="00000007"/>
    <frame level="42"/>
    <frame level="43"/>
    <frame level="44" function="g_closure_invoke" offset="000001aa"/>
    <frame level="45"/>
    <frame level="46" function="g_signal_emit_valist" offset="000007ec"/>
    <frame level="47" function="g_signal_emit" offset="00000090"/>
    <frame level="48"/>
    <frame level="49"/>
    <frame level="50" function="gtk_main_do_event" offset="0000115c"/>
    <frame level="51"/>
    <frame level="52"/>
    <frame level="53" function="g_main_context_dispatch" offset="0000027e"/>
    <frame level="54"/>
    <frame level="55" function="g_main_loop_run" offset="00000083"/>
    <frame level="56" function="gtk_main" offset="0000007f"/>
    <frame level="57" function="wxGUIEventLoop::DoRun()" offset="00000026"/>
    <frame level="58" function="wxEventLoopBase::Run()" offset="0000002e"/>
    <frame level="59" function="wxAppConsoleBase::MainLoop()" offset="00000057"/>
    <frame level="60" function="wxEntry(int&amp;, wchar_t**)" offset="00000048"/>
    <frame level="61"/>
    <frame level="62" function="__libc_start_main" offset="000000f3"/>
    <frame level="63"/>
  </stack>
</report>

```
</details>

**Comment by vomikan** [comment]
Related issue: #1802

**Comment by roi859** [comment]
Another related issue: #1811 

Please see my comment: https://github.com/moneymanagerex/moneymanagerex/issues/1802#issuecomment-544527944

Today i  built the app by myself, hopefully to solve this years old problem that makes mmex nearly unusable, but nothing changed. The app crashes as usual.

After more than 2 years and countless issues opened about this problem, which make using the app exteemely frustrating, i think it's time for me to acknowledge the mmex team is not able to/not interested in fixing this issue. **Please consider warning users about the fact that mmex is almost unusable on some Linux distros** (i tried it in at least 3, broken in all of them).

I would have switched to something else long ago, but i have a lot of data in mmex that i don't want to lose. Is there some safe way to export the database to gnucash? I couldn't find anything.

**Comment by vomikan** [comment]
I used to use Linux with great pleasure and admired the creativity of this product. Inside the Linux world, all problems are solved by the community and not always immediately.
Initially, I even programmed an mmex from under the requesting editor in Ubuntu. I wrote on the forum that if you have a problem, then build the mmex in debug mode and investigate where the failure occurs. (This is a rather time-consuming operation and requires a lot of time to study). Accordingly, no one did this.
Next, I switched to Visual Studio. This is a amazing product that allows you to program with great convenience and speed. For open course projects, this development environment is provided completely free !!!
Since then, Linux has left my desktop (for the most part, this was affected by the work and programs of the employer).
mmex multi-platform program (works in Linux, MAC and Windows). But most users and developers work with Windows (because VS is the coolest).
Now we have 1% Linux users, 5% MAC and 94%LWindows users.
Most popular Windows 10 has 64 release and support 32 bit apps as well.
MAC has one newest release and some old releases.
Linux has about 20 different distros.... look at this https://travis-ci.org/github/moneymanagerex/moneymanagerex/builds/681187594

We are waiting for a hero who will emerge from this one percent of users and one more will be a programmer from God and fix everything.

Perhaps it will be you!

**Comment by roi859** [comment]
> We are waiting for a hero who will emerge from this one percent of users and one more will be a programmer from God and fix everything.

I'm not asking or expecting the problem to be fixed. When a fundamental issue such this one doesn't get fixed in years, but releases still come out, it's clear that devs are not able/interested in fixing the problem. This is an open source project, devs are free to work on whatever they want and leave bugs if they want to, what it's not acceptable is to leave some users on their own, advertising linux compatibility when it's not really the case.

What i'm asking, again, is: Warn linux users that this app may not work on their distro or simply remove linux support.

Right now i'm stuck with mmex because i cannot migrate such big database to another app without losing important data and i want to avoid other linux users to find themselves in the same situation. Please let me know if there is a way to export the mmex database to another money managing app like gnucash.

**Comment by vomikan** [comment]
There are 3 options:
1) csv file (some data will be lost.
2) QIF (with some restrictions as well
3) Excel something like point 1 but may be opened by MS Excel program.
4) JSON Export. New Feature in 1.3.4. I am planning to extend this function to export everything from mmex to JSON file.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/80771289-9ff2dd80-8b5b-11ea-9344-a424df68ca74.png)


![image](https://user-images.githubusercontent.com/6836805/80770777-e47d7980-8b59-11ea-8d28-c161f06d259e.png)

**Comment by vomikan** [comment]
@roi859 @feimosi 
Possible, this issue fixed in case 2470.
I've build mmex using instractions from the following case: https://github.com/moneymanagerex/moneymanagerex/issues/2470

By default most Linux distros used wx3.0.4 but for mmex better to have wx3.1.3.
The build is stable enougt.

**Comment by feimosi** [comment]
FYI I'm still experiencing this issue, even after updating to v1.3.6.

**Comment by vomikan** [comment]
@feimosi  please provide OS vertion details and WX info

**Comment by feimosi** [comment]
It's the following:

```
Version: 1.3.6 64-bit
• Database version: 7 • (aes128cbc)

MMEX is using the following support products:
• wxWidgets 3.0.5 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.2
• libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0

Build on Dec 26 2020 12:25:44 with:
• CMake 3.19.2
• GNU Make 4.3
• gettext 0.21
• GCC 10.2.0 • Arch rolling

Running on:
• Arch Linux "n/a"
• Linux 5.10.3-arch1-1 x86_64
```

Unfortunately wx3.1 [is not compatible](https://archlinux.org/todo/wxgtk-31-rebuild/) with Arch.
I understand it's hard to fix, so I don't expect anything. Just wanted to update this thread.
