### ISSUE TITLE
Settings DB already running

### ISSUE THREAD

**Issue by Kidkroco** [moneymanagerex/moneymanagerex#2423]
- Check OS
  - [X] Mac OSX 10.15.4
-  Check MMEX version
  - [X] 1.3.4

Hello guys,

Let me start by thanking you for this great app that I've been using for five years at least and saying that I am not a technical guy. I installed the 1.3.4 on my iMac and I started by having the issue that says the app is damaged. I installed and re-installed the app several times, then I found online a command to enter in the terminal and it worked....for a day.

Now when I open the app I receive a first message:

_MMEX Instance check. Settings DB is already opened by another instance of MMEX...._

I click on continue and I get the next message:

_Database that you are trying to open is already opened by another instance of MMEX._

Then I click on continue, the app opens but I immediately get the next message window:

_Debug report review_, there is a debug report. I can click on cancel or ok and no matter what I do the app crashes immediately.

I tried restarting my Max obviously. I also tried re-installing the app.

Would you be able to help me ? Your app is too useful I can't live without it now !!! :-)

**Comment by vomikan** [comment]
First, I want to thank you for the kind words addressed to our application and for the high appreciation of our work.

Regarding the case https://github.com/moneymanagerex/moneymanagerex/issues/2387 I've created a simple experimental feature to avoid usage of DB at the same time from others instances of mmex. 
On Windows it's quite easy to run several mmex at the same time. It's begin available in 1.3.4.
Both massages that you have received it's just information. On crash the app does not clear "usage" bit.

But  Debug report  appears when app has crashed. 
Possible reason is auto recurring transactions. https://github.com/moneymanagerex/moneymanagerex/issues/2416

**Comment by Kidkroco** [comment]
Is there anything I can do to prevent the crash ? I've got the same messages and same final crash every time I try opening the app.

**Comment by vomikan** [comment]
Could you try ti install this version?
[mmex-1.3.5~beta2-Darwin.dmg.zip](https://github.com/moneymanagerex/moneymanagerex/files/4535461/mmex-1.3.5.beta2-Darwin.dmg.zip)

**Comment by user8446** [comment]
To add to this on my machine (W10) I only receive this error if MMEX is closed via command line: `Stop-Process -Name mmex` and then reopened. If I close MMEX in the program itself it closes out the settings db correctly and on the next start the error does not appear.

I need the command line start and close because I have task scheduler matching the automated recurring transactions in MMEX so they can automatically post and the database is synced to other devices. 

Thank You

**Comment by Kidkroco** [comment]
> Could you try ti install this version?
> [mmex-1.3.5~beta2-Darwin.dmg.zip](https://github.com/moneymanagerex/moneymanagerex/files/4535461/mmex-1.3.5.beta2-Darwin.dmg.zip)

Thanks. It fixed my issue. It might indeed be due to the recurring transactions since I had one that came at maturity yesterday. When I open the app, I now receive the "recurring transaction maturity date notification". I suppose this notification was generating the problem.

Thank you very much

**Comment by vomikan** [comment]
Anyway, there is annoying bug in v1.3.4 especially for MAC.
In 1.3.5 I've fixed some errors already.

**Comment by user8446** [comment]
I just tested 1.3.5 beta 2 for Win64 bit and the same issue persists.

**Comment by vomikan** [comment]
Other worlds, you started mmex from scheduler to automatically post all recurring transactions then kill the process?
Few could think of such a creative solution.

**Comment by user8446** [comment]
That's correct, it starts and waits 10 seconds then kills it. All recurring transactions are posted and the db is updated.

**Comment by marty008** [comment]
Using 1.3.4 on Win 64. Have same error. Cannot get round even after system reboot. (Have lots of recurring). Crashed whilst attempting edit of Payee description. As with others , I need urgent workround as totally dependent on mmex. Thanks

**Comment by vomikan** [comment]
To proper solve your issue it should be some parameter to execute only recurring transactions (+ web app, possible). 

Right now I can delete this options and release binary file for you.

https://github.com/moneymanagerex/moneymanagerex/commit/17e236021adbb01a8ab3489dcf0f502effdf1a84#diff-4c1142bf1ba27682b8dfed154c0c56a3

**Comment by user8446** [comment]
@marty008 What about just downgrading to 1.3.3?

**Comment by vomikan** [comment]
@marty008 you could to start mmex with -s parameter to avoid a dialogue at start.
