### ISSUE TITLE
1.4.0 crash on Fedora 32

### ISSUE THREAD

**Issue by sebw** [moneymanagerex/moneymanagerex#2461]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] mmex-1.4.0_alpha.7-1.fc30.x86_64.rpm
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

After upgrading to Fedora 32, mmex crashes:

`mmex: symbol lookup error: mmex: undefined symbol: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEC1EPKwRKS3_, version WXU_3.0`

**Comment by sebw** [comment]
Just tested `mmex-1.3.5.beta4-1.fc30.x86_64.rpm` and it crashes too.

**Comment by vomikan** [comment]
what is wx version?

**Comment by vomikan** [comment]
I recommend to build from scratch using instructions from docker files
https://github.com/moneymanagerex/moneymanagerex/tree/master/dockers

**Comment by sebw** [comment]
wxBase3-3.0.4-13.fc32.x86_64
wxGTK3-3.0.4-13.fc32.x86_64
wxGTK3-i18n-3.0.4-13.fc32.noarch

I'll give Dockerfile a shot, thanks!

**Comment by vomikan** [comment]
MAC and Windows builds has build base on wx 3.1.3
Most Linux distros till use wx 3.0.4.

sample:
https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.5/.travis.yml#L112-L118

**Comment by vomikan** [comment]
I've build mmex using instractions from the following case: https://github.com/moneymanagerex/moneymanagerex/issues/2472

It's working stable. #2470

**Comment by jota2016** [comment]
Hi,
Same issue here with Fedora32 (mmex-1.3.4-1.fc30 and mmex-1.3.5~beta5-1.fc30). One question. Why is it working on Fedora 31 with wx 3.0.4-10 and not with 3.0.4-13?

**Comment by vomikan** [comment]
I will not be able to answer this question, unfortunately.

Debugging on Linux is a quite difficult task.
Look at the video:
https://github.com/moneymanagerex/moneymanagerex/issues/2483 (zip file)

**Comment by vomikan** [comment]
A lot of critical issues has been fixed right now.
I suggest to test mmex v 1.3.5-beta.7 (will be available soon).

**Comment by jota2016** [comment]
HI,
With 1.3.5-beta.7-1 and with 1.3.5~rc1-1 the issue is still present on Fedora 32. I have tried with wx 3.0.5.1-1 from Rawhide with same result.

**Comment by vomikan** [comment]
I think is only solution install wx3.1.3 and build mmex from sources.

**Comment by jota2016** [comment]
wx3.1.3 is a development branch that is not yet supported by Fedora. You can compile from source, but, I think it's safer to install Fedora 31 packages, than that works. This can only be done if no other packages use them as dependencies. The working packages are wxBase3-3.0.4-10.fc31.x86_64  wxGTK3-3.0.4-10.fc31.x86_64  wxGTK3-i18n-3.0.4-10.fc31.noarch and  wxGTK3-webview-3.0.4-10.fc31.x86_64.

**Comment by vomikan** [comment]
Related issue
https://github.com/moneymanagerex/moneymanagerex/issues/1903
