### ISSUE TITLE
Transaction Report settings name utf8 support

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3325]
>**Problem: Transaction report name is not saved**
1. Clicked on Transaction Report (left panel) -> Transaction filter open
2. Selected Date Range from 01/04/2021 till 30/042021 -> Date Range is selected
3. Chose Category -> Category is selected
4. Checked the box Included Similar -> The checkbox selected
5. At the drop-down list choose 1:Empty -> 1:Empty choosen
6. Clicked at Save button -> Setting name popup open
7. Changed 1:Empty to 1:Food and clicked OK -> Popup closed, at the drop-down Settings is shown 1:Food
8. Clicked OK button -> Transaction Filter popup closed, correct Transaction Report is shown on the screen.
9. Clicked on Transaction Report (left panel) again -> Transaction filter open
10. Date Range and Categories keep entered data, **but 1:Food in the drop-down list was not saved. Instead, there is 1:Empty**
> Please do not remove the information attached below this text.

<hr>Version: 1.5.1 64-bit<br>
 • Build: Apr 24 2021 14:32:48<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19041), 64-bit edition<br>
 •   (windows-1255)<br>
 • 1536x864 32bit 96x96ppi

**Comment by vomikan** [comment]
Thank you for your report.
I can't reproduce this issue. 
This requires further investigation of the reasons for this behavior of this function.

![image](https://user-images.githubusercontent.com/6836805/115992186-ffe85c80-a5d4-11eb-8dc1-8f5e4d74a8e7.png)

**Comment by Dandy64** [comment]
Well, I am ready to assist. I have repeated all the steps a few times with the same result.
Please, see attached screenshots from 1 to [5.[](![1](https://user-images.githubusercontent.com/83161661/115994405-7b4f0b80-a5df-11eb-9c48-dc7f8eabd236.JPG))]([url](url
![2](https://user-images.githubusercontent.com/83161661/115994406-7c803880-a5df-11eb-9185-7fc74685517a.JPG)
![3](https://user-images.githubusercontent.com/83161661/115994407-7d18cf00-a5df-11eb-8de4-82c6e195823e.JPG)
![4](https://user-images.githubusercontent.com/83161661/115994408-7d18cf00-a5df-11eb-8ee2-d6b557c3d9d7.JPG)
![5](https://user-images.githubusercontent.com/83161661/115994409-7db16580-a5df-11eb-827b-c10510c93208.JPG)



))

**Comment by Dandy64** [comment]
I see the difference just in dates - I don't think it is matters. And the Category name is in Russian.

**Comment by Dandy64** [comment]
I have found the problem is. 
I took a new application and a new DB. Created 2 test transactions and after that created Transaction Report. Everything was fine and the report saved with no problems.
After that, I have changed one of the Category names to **Russian** language and also changed the subcategory name.
**The Report failed to save.**

**Comment by vomikan** [comment]
Спасибо, товарищ!

**Comment by Dandy64** [comment]
Sorry to say, but it still doesn't work. I tested a new version 1.5.2.

**Comment by vomikan** [comment]
Fixed

**Comment by Dandy64** [comment]
Sorry, but it still doesn't work. It is not a big deal for me, but anyway it looks like a bug.
If a category name was written on any Cyrillic language the report will not be saved. If I change the name to English everything saved with no problem.
