### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by camposFabio** [moneymanagerex/moneymanagerex#3631]
MMEX version:
 - [X] 1.5.x 
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X] Linux 

# Description of the bug

Calling MMEx from the terminai I got the following error:

19:24:15: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1016,wx containers,compatible with 2.8).
[1]    39209 killed     mmex

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Compile source
2. Execute

…

Expected result:
Program run

Actual result:
Out of Memory error.

![Captura de tela de 2021-06-17 19-50-39](https://user-images.githubusercontent.com/40764894/122481620-5fdffb80-cfa5-11eb-903b-73f79e6dc5a0.png)

# Additional information
- Arch Linux
- mmex-1.5.4.Beta.1-1
- cmake -DCMAKE_BUILD_TYPE=Release .. -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-gtk3
-- Found wxWidgets: -pthread;;;-lwx_gtk3u_core-3.0;-lwx_gtk3u_qa-3.0;-lwx_gtk3u_html-3.0;-lwx_baseu_xml-3.0;-lwx_gtk3u_aui-3.0;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_stc-3.0;-lwx_gtk3u_webview-3.0;-lwx_baseu-3.0 (found suitable version "3.0.5", minimum required is "2.9.2") 
-- Checking for one of the modules 'libcurl'
-- Found CURL: /usr/lib/libcurl.so (found version "7.77.0")
-- Version: 7.1.4
-- Build type: Release
-- CXX_STANDARD: 11
-- Required features: cxx_variadic_templates
-- Found RapidJSON: /home/fabio_HD/Projetos/moneymanagerex/3rd/rapidjson/include
-- Found wxSQLite3: wxcode_gtk3u_wxsqlite3-3.0 (found version "4.7.2")
CMake Warning at 3rd/CMakeLists.txt:167 (message):
  wxSQLite3 found does not support database encryption - compiling from
  sources

CMake Deprecation Warning at CMakeLists.txt:731 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- 
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.4-Beta.1
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : Release
-- Generator      : Unix Makefiles
-- Install prefix : /usr
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.12.10-arch1-1
-- Arch 5.12.10-arch1-1
-- CMake 3.20.4
-- GNU Make 4.3
-- ccache
-- GNU 11.1.0
-- wxWidgets 3.0.5
-- wxSQLite3 4.7.2
-- Lua 5.4.3
-- curl 7.77.0
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done
***************************************

journalctl -b 0 | grep -i mmex
```
jun 17 19:23:52 arch dbus-daemon[412]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.146' (uid=0 pid=39098 comm="sudo pacman -U mmex-1.5.4.Beta.1-1-x86_64.pkg.tar.")
jun 17 19:23:52 arch sudo[39098]:    fabio : TTY=pts/3 ; PWD=/home/fabio_HD/Projetos/moneymanagerex/build ; USER=root ; COMMAND=/usr/bin/pacman -U mmex-1.5.4.Beta.1-1-x86_64.pkg.tar.zst
jun 17 19:24:12 arch dbus-daemon[412]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.149' (uid=0 pid=39171 comm="sudo pacman -U mmex-1.5.4.Beta.1-1-x86_64.pkg.tar.")
jun 17 19:24:12 arch sudo[39171]:    fabio : TTY=pts/3 ; PWD=/home/fabio_HD/Projetos/moneymanagerex/build ; USER=root ; COMMAND=/usr/bin/pacman -U mmex-1.5.4.Beta.1-1-x86_64.pkg.tar.zst
jun 17 19:27:01 arch kernel: [  39209]  1000 39209 13278356  3247050 50794496  3041498             0 mmex
jun 17 19:27:01 arch kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-314c4f71-effb-404e-9e74-884c0ca0f0ff.scope,task=mmex,pid=39209,uid=1000
jun 17 19:27:01 arch kernel: Out of memory: Killed process 39209 (mmex) total-vm:53113424kB, anon-rss:12988192kB, file-rss:4kB, shmem-rss:4kB, UID:1000 pgtables:49604kB oom_score_adj:0
jun 17 19:27:04 arch kernel: oom_reaper: reaped process 39209 (mmex), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
jun 17 19:52:33 arch kernel: [  42017]  1000 42017 13280407  3088166 49668096  3058185             0 mmex
jun 17 19:52:33 arch kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-314c4f71-effb-404e-9e74-884c0ca0f0ff.scope,task=mmex,pid=42017,uid=1000
jun 17 19:52:33 arch kernel: Out of memory: Killed process 42017 (mmex) total-vm:53121628kB, anon-rss:12352660kB, file-rss:0kB, shmem-rss:4kB, UID:1000 pgtables:48504kB oom_score_adj:0
jun 17 19:52:36 arch kernel: oom_reaper: reaped process 42017 (mmex), now anon-rss:0kB, file-rss:0kB, shmem-rss:4kB

```

If you have a backtrace for a crash or a warning, paste it here.

**Comment by camposFabio** [comment]
Fixed on the latest build. 
But now, when entering an new entry,  it does not respect the date format chose on settings.

Output:
16:31:01: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1016,wx containers,compatible with 2.8).

(WebKitWebProcess:98208): Atk-CRITICAL **: 16:31:13.376: atk_state_set_contains_state: assertion 'ATK_IS_STATE_SET (set)' failed
(WebKitWebProcess:98208): GLib-GObject-CRITICAL **: 16:31:13.377: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(WebKitWebProcess:98208): Atk-CRITICAL **: 16:31:13.377: atk_state_set_contains_state: assertion 'ATK_IS_STATE_SET (set)' failed
(WebKitWebProcess:98208): GLib-GObject-CRITICAL **: 16:31:13.377: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(WebKitWebProcess:98208): Atk-CRITICAL **: 16:31:13.401: atk_state_set_contains_state: assertion 'ATK_IS_STATE_SET (set)' failed
(WebKitWebProcess:98208): GLib-GObject-CRITICAL **: 16:31:13.402: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(WebKitWebProcess:98208): Atk-CRITICAL **: 16:31:13.402: atk_state_set_contains_state: assertion 'ATK_IS_STATE_SET (set)' failed
(WebKitWebProcess:98208): GLib-GObject-CRITICAL **: 16:31:13.402: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by camposFabio** [comment]
The memory problem returned. It appears something intermittent. There should be some leak somewhere. I'will try to debugg the code to find more info.
I rolled back do 1.3.6 and the problem is over.

**Comment by PMaff** [comment]
Does that bug still exist in the latest 1.5.12 stable version?

**Comment by PMaff** [comment]
What if you use wxWidgets 3.1.5 ?

**Comment by camposFabio** [comment]
I'm using the latest version (compilled from source) and everything is ok
