### ISSUE TITLE
Separation of numbers

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#3925]
It could be resolved to display the numbers (money) in both the main page (at startup) and in the reports wherever the amount of money is visible. Like this:
1 213 192
163 799
49 393
298 170
3 096 083
202 087
1 480

**Comment by whalley** [comment]
Will it not allow you to remove the locale from the options and leave blank? Then change the currency grouping char to " " (single space)?

**Comment by jkuj6** [comment]
This is indeed still an issue in v1.5.13 - Ubuntu 20.04

If i use Locale as shown here, then it still doesnt separate the numbers.
![2022-03-10_locale](https://user-images.githubusercontent.com/59932002/157675498-aaa3e260-fb17-4bc7-b20c-5d6d65dfbfff.jpg)
![grouping_char_locale](https://user-images.githubusercontent.com/59932002/157675595-2febc11a-d000-4c01-9dad-2bd7610501a2.jpg)

If i use blank Locale as shown here, and try to put a space or a comma under `grouping char` it still doesnt display it in the numbers at all. Even after restarting the app.
![grouping_char](https://user-images.githubusercontent.com/59932002/157675542-dd2966af-f0e8-4a52-b233-ba73a6bed1d6.jpg)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4191

**Comment by ovari** [comment]
@Heny67 which version of MMEX are you using? The UI should be completely translated into Hungarian.

**Comment by ovari** [comment]
@jkuj6 how do you bring up `Currency Manager` in MMEX?

![image](https://user-images.githubusercontent.com/17465872/217927780-22a742be-a876-4364-83f8-3e0b86a225ad.png)

The string [Currency Manager](https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=currency%20manager) isn't in Crowdin.

Thank you

**Comment by tactilis** [comment]
>

`Tools | Organize Currency...` (or click on the toobar icon) and then `right-click | Edit` the currency (or just double click it)


![image](https://user-images.githubusercontent.com/4060092/217961991-6ac58d5a-4de6-4db2-a8b0-bee0b4ba98dc.png)

**Comment by whalley** [comment]
@Heny67 Not sure from reading histroy whether this is fixed or not? Can you confirm.

**Comment by n-stein** [comment]
I think this may have been resolved by #6074

**Comment by Heny67** [comment]
> @Heny67 Not sure from reading histroy whether this is fixed or not? Can you confirm.

@whalley On 1.6.4, the number separation still appears incorrectly, but on 1.7.0 it is fine, I have display problems there (Nvida +Webkit error)
