### ISSUE TITLE
Filters do not take into account transactions where the categories are split

### ISSUE THREAD

**Issue by Dellyes** [moneymanagerex/moneymanagerex#4698]
Dans la Liste des opérations le résultats des filtres ne tiennent pas compte des opérations où la catégorie a été répartie

<hr>Version: 1.5.15 64-bit<br>
 • Build: Juin 16 2022 09:13:44<br>
 • db 7 •  (aes128cbc)<br>
 • git e7bb96c (2022-06-16)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  French (windows-1252)<br>
 • 1360x768 32bit 96x96ppi

**Comment by tactilis** [comment]
The title says:  **"In the list of operations, the results of the filters do not take into account operations where the category has been distributed"**

@Dellyes
1. You will need to provide more information. The nature of the problem you are having is not clear.
Please report bugs on this form [https://github.com/moneymanagerex/moneymanagerex/issues/new/choose](https://github.com/moneymanagerex/moneymanagerex/issues/new/choose) and provide the information requested.

**Comment by whalley** [comment]
There was an error with split transactions, that was fixed here: https://github.com/whalley/moneymanagerex/commit/9a6b83208b739b3f98e95b6a390fafa3b8bc5337

Can you try the latest beta build. https://moneymanagerex.org/docs/downloads/development/

**Comment by Dandy64** [comment]
Sorry, but the problem still exists.
Last version 1.5.18, Windows, Portable, 64 bit

Steps.
1. Created a new DB with just 1 account - Bank
2. Created 2 transactions:
  
1 transaction:   
![image](https://user-images.githubusercontent.com/83161661/182024031-293ee1c3-405d-42de-b900-f282d85582b6.png)
   
                                            
2 Transaction                                            
![image](https://user-images.githubusercontent.com/83161661/182023988-0ad63fec-5fa7-4fa9-8d50-c645be826aa4.png)

Total - 350:
![image](https://user-images.githubusercontent.com/83161661/182024108-4cfe2b01-9112-4ac6-acac-bd39ee77a448.png)

3. Created Transaction filter
![image](https://user-images.githubusercontent.com/83161661/182024156-dd566596-f26c-4cdc-b5f6-2a1df34e368f.png)

**Expected result:**  - 150 + 200 = 350
**Actual result:**
![image](https://user-images.githubusercontent.com/83161661/182024254-5d55e662-450b-4bc2-98f3-6cdbc2069a34.png)

**The split transaction was not taken into account.**

**Comment by whalley** [comment]
Adding 
          `  if (dlg.get()->mmIsCategorySubCatChecked()) value = value + ".*";`

after: https://github.com/moneymanagerex/moneymanagerex/blob/634981907f15b3ea2f1d4ee3f020b39a9d252eda/src/reports/transactions.cpp#L398

should possibly fix it (need to remove the const also)

**Comment by vomikan** [comment]
> Adding ` if (dlg.get()->mmIsCategorySubCatChecked()) value = value + ".*";`
> 
> after:
> 
> https://github.com/moneymanagerex/moneymanagerex/blob/634981907f15b3ea2f1d4ee3f020b39a9d252eda/src/reports/transactions.cpp#L398
> 
> should possibly fix it (need to remove the const also)

I think I did it in my own way.

**Comment by tauchmi** [comment]
It seems with 1.6.2 (64 bit) this is again an issue. You can simulate it easily with a new database.

It seems it only happens when I filter by a top category and select "Include all sub-categories".
[test.zip](https://github.com/moneymanagerex/moneymanagerex/files/10374329/test.zip)

**Comment by n-stein** [comment]
@vomikan I see this is closed again but I didn't see a fix. If it is already handled let me know and I'll close PR #5515.

**Comment by vomikan** [comment]
> @vomikan I see this is closed again but I didn't see a fix. If it is already handled let me know and I'll close PR #5515.

Unfortunately, I got confused in this case. I saw your comment after that I closed the case.
If something went wrong, feel free to fix it.
