### ISSUE TITLE
Use default for Payee and Last used for Payee seems to be broken

### ISSUE THREAD

**Issue by CDevel** [moneymanagerex/moneymanagerex#4879]
Dear MMEX team,
Sorry If anyone has already reported the specific problem, but I can't find anything relative in the issues section.
For the last 2-3 versions, it seems that when I am adding a transaction and select a Payee from the list control, MMEX cannot automatically set the last used or the default category for the specific payee. I have used Organize Payees to verify that all my transactions have a default category but unfortunately the Add Transaction dialog box seems to ignore the settings. So I have to set manually the category each time.

Kind regards
Yiannis

<hr>Version: 1.5.18 64-bit<br>
 • Build: Jul 27 2022 22:24:57<br>
 • db 7 •  (aes128cbc)<br>
 • git 6dba91a (2022-07-28)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  Greek (Greece) (windows-1252)<br>
 • 3840x2160 32bit 96x96ppi

**Comment by whalley** [comment]
Can you confirm what these settings are please:

![CleanShot 2022-07-28 at 18 56 46](https://user-images.githubusercontent.com/487345/181605374-17b9943a-7b2f-4fee-b08a-2f60c03cf528.png)

**Comment by CDevel** [comment]
Hi Whalley,

I can confirm that I have used both choices
A. Use last category used
B. Use default for payee.

Unfortunately i cannot send screenshot since I am going to be on vacation the next few days.
Sorry for the bad timing reporting the error.
As soon as I return I will provide more info

Best regards
Yiannis

**Comment by whalley** [comment]
Seems fine on Windows also...

![CleanShot 2022-07-28 at 23 44 50](https://user-images.githubusercontent.com/487345/181649726-d2c8374e-9048-42b1-8aab-74f250a9fd2d.gif)

**Comment by CDevel** [comment]
Is there a chance that it could be that I am using Greek locale? When I am back I will test it on my laptop (again Windows 10) to see if it is device dependent error and will also create a few English entries to test.

**Comment by CDevel** [comment]
Hi Whalley,

Back in my office for a few days. I installed the latest version on my laptop and the behavior is the same. 
Though, I noticed something and that is why I am attaching two examples to present the error that I have found. 
It seems that the error occurs on the first time the dialog opens. When I select a payee, the category automatically selected is wrong. Without closing the dialog I select a random payee and then back the one that I want and that time the filtering brings the correct default category. I say default cause that is my choice on the settings. 
Hope that helps somehow. 

Kind regards
Yiannis

![2022-08-09-18-19-54](https://user-images.githubusercontent.com/35450092/183690200-25886195-1f04-4555-9c26-6e892483a72e.gif)
![2022-08-09-18-20-44](https://user-images.githubusercontent.com/35450092/183690233-5b691966-85ba-424c-ab8f-2f59e029c6fb.gif)

**Comment by whalley** [comment]
I cannot actually work out what is incorrect in the recordings.... (it maybe the greek confusing me!). But if you tab to the next field after the payee does that work? See: https://github.com/moneymanagerex/moneymanagerex/issues/4886

**Comment by vomikan** [comment]
@CDevel could you, please, show the version?

**Comment by CDevel** [comment]
Hi guys,

Version Screenshot
![image](https://user-images.githubusercontent.com/35450092/183892447-e8ca5e4d-7784-436d-a7dd-4ad140c1ebe3.png)

Also added three new payees with some dummy categories
![image](https://user-images.githubusercontent.com/35450092/183892624-39713e57-200a-4744-9b48-8b8cdb48753a.png)

Testing with the English named payee and category
![2022-08-10-14-42-31](https://user-images.githubusercontent.com/35450092/183892878-e28d1c29-a875-461b-8a4b-456a715abff5.gif)
![2022-08-10-14-44-01](https://user-images.githubusercontent.com/35450092/183893062-cdc711f4-c4c6-46cc-8b8f-933524ac25f2.gif)

As you can see I select the Milk Shop Entry and initially it brings some random category. When I change the selection to something different and then back to Milk Shop the default category appears correctly.

Regards
Yiannis

**Comment by vomikan** [comment]
I fixed it in the case https://github.com/moneymanagerex/moneymanagerex/issues/4886

You could test it 
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44420925/job/yvh6dvgmf6erl3p4/artifacts

**Comment by CDevel** [comment]
Hi vomikan

Have downloaded and tested the recommended fixed version. It seems that the English labeled entries works properly while my Greek entries are still getting confused.

**Comment by vomikan** [comment]
> Have downloaded and tested the recommended fixed version. It seems that the English labeled entries works properly while my Greek entries are still getting confused.

For me, it works the same way with both Latin characters and Cyrillic.
Only one problem has not been fixed. After you start typing something, then select with the mouse, then the category does not change. Press Tab.

**Comment by CDevel** [comment]
Thanks for the reply vomikan. 
I will play arround a bit with the selection of payee either by typing or using mouse and I will report anything weird as soon as I figure out what is going wrong.

Regards
Yiannis

**Comment by PMaff** [comment]
I am also missing the usage of last used category for "Zahlungsempfänger/Zahler"  == Payee for some past versions now and this is also a problem here in stable 1.5.18 on Ubuntu 18.04  Linux.
I did not find a corresponding issue for that.
