### ISSUE TITLE
Unexpected space added to Category filter when Regex is used to include multiple sub categories

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5392]
MMEX version:
 - [x] 1.6.1

I have a category named "Home Projects" with multiple sub-categories. I wanted to create a report that would show the "Porch 2021" and "Porch 2022" subcategories only. I also have some transactions categorized directly under "Home Projects" only that I do not want to include and have other sub categories, so the "Include all sub-categories" checkbox doesn't meet my needs.

![image](https://user-images.githubusercontent.com/95182117/205172599-e95c0df8-da45-4e91-9f34-25d3bca2ec47.png)

So I created (and saved) the following transaction filter and it worked perfectly:
![image](https://user-images.githubusercontent.com/95182117/205173025-5947f91c-586d-44bc-b3ce-89aa96b2eada.png)

However the next time I ran the filter, no transactions were displayed. Upon looking closer, I discovered an extra space was added after the : delimiter when I ran or opened the filter:
![image](https://user-images.githubusercontent.com/95182117/205173237-fc1a5fd2-73f1-48f7-8c84-1e61b21402da.png)

I also confirmed this in the database (after saving):
![image](https://user-images.githubusercontent.com/95182117/205173712-590c80e8-7b05-4826-b766-9ce66fdd71a2.png)

My current workaround is to use this Regex which avoids the category delimiter and there is no issue. This works but I thought I would share incase others are impacted by this behavior
![image](https://user-images.githubusercontent.com/95182117/205173950-7304288d-809a-4e39-82e4-b029c7634c3d.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 
Also see #5391

**Comment by n-stein** [comment]
Fixed in PR #5398

**Comment by n-stein** [comment]
I think this also fixes #5391

**Comment by rmelillo76** [comment]
Thanks @n-stein, unfortunately the problem still persists in the latest build after your change.
To confirm, my original regex is

`Home Projects:  Porch.*`

and my delimiter is  `": "`

![image](https://user-images.githubusercontent.com/95182117/205771598-316f722f-52b4-4694-b72a-5a05ad6cc782.png)


The filter works initially but then it gets saved with an extra space

![image](https://user-images.githubusercontent.com/95182117/205771482-2bd7e72c-0f44-4f63-9aa6-812617c4eb10.png)

Causing the report to not work:

![image](https://user-images.githubusercontent.com/95182117/205772285-9c97bbb1-e2ae-4f06-a16c-f278456591c7.png)

**Comment by rmelillo76** [comment]
And as I test this some more, I realize that each time I open the filter dialog an additional space is added:

`Home Projects:  Porch.*`
`Home Projects:   Porch.*`
`Home Projects:    Porch.*`

**Comment by rmelillo76** [comment]
And as I test this some more, I realize that each time I open the filter dialog an additional space is added:
![image](https://user-images.githubusercontent.com/95182117/205773181-1fb3c0fa-ffee-41a6-a5ae-aae9c9a9f0bb.png)
![image](https://user-images.githubusercontent.com/95182117/205773206-1d5858fc-c5be-4cce-9e6a-a95ebdc0cf25.png)
![image](https://user-images.githubusercontent.com/95182117/205773225-d8e1c334-7256-4abb-8b89-70531a0f3b6d.png)
etc...

**Comment by n-stein** [comment]
Which build did you test? You need to test 5928. Build 5929 contains a fix for a different issue, doesn't contain this code fix.

**Comment by rmelillo76** [comment]
> Which build did you test? You need to test 5928. Build 5929 contains a fix for a different issue, doesn't contain this code fix.
> 
> Here: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/45583834

Thanks @n-stein, that did the trick. Confirmed working now!
