### ISSUE TITLE
Reconciled Net Worth Total at Top of Homepage, Don't Match Reconciled Acct. Totals

### ISSUE THREAD

**Issue by dobber1** [moneymanagerex/moneymanagerex#6043]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3 Beta
 - [x ]1.6.4 Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11 64 bit
 - [ ] Mac OSX
 - [ ] Linux 

Reconciled Net Worth Total at Top of Homepage, Don't Match Reconciled Acct. Totals with the rest of the home page. 

This is with the new version 1,6.4..  Version 1.6.3 this problem did not exist. Top of home page matched acct. totals below on the home page. 

Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps: Open Homepage

Expected result: Acct. totals to match net worth totals at top of homepage.

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
I can't reproduce this. My main database and my test databases have Account totals and Net Worth totals that match.

@dobber1 Could you post a screenshot showing the incorrect figures please?

**Comment by whalley** [comment]
> I can't reproduce this. My main database and my test databases have Account totals and Net Worth totals that match.

Ditto... looks fine to me.

**Comment by migliosa** [comment]
I am experiencing the same issue with version 1.6.4, no problem going back to 1.6.3
Reconciled Net Worth Total is negative

**Comment by n-stein** [comment]
I suspect this is because the Net Worth on the homepage now includes the balances of share accounts as changed in #5834. Do you have share accounts with large negative balances?

**Comment by vomikan** [comment]
Maybe it's about Showing future transactions?

**Comment by tactilis** [comment]
@dobber1
This is unrelated to the problem you have reported, but are you aware that at some point in the past (in 2017), you opened and started using a backup of your database as though it was your 'working' database?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/79b48f78-a17c-458a-baf1-7f6b3170aec9)

You had a database called 'Bob & Cathy Finance.mmb' (see the bit I've underlined in red).

When you exited MMEX, a backup copy was saved as 'Bob & Cathy Finance.mmb_update_2017_01_31.mmb'  (red and green underline).

This was in the days when backups had a file type of .mmb so could be directly opened by accident as it appears you did.

Nowadays, backups are named with a file type of .bak to prevent this.

I would suggest that to rationalise the naming, you copy your 'Bob & Cathy Finance.mmb_update_2017_01_31.mmb' (assuming that _is_ your current database) to 'Bob & Cathy Finance.mmb' and always use that from now on.

**Comment by dobber1** [comment]
Thank You Very much !! I appreciate your help, I didn't realize I was doing that all these years. I will see what i can do to copy to the other database. Thanks again, keep up the good work.

**Comment by n-stein** [comment]
I see this is closed, but I didn't catch the resolution. I see a few others in the forum are reporting the same problem. What was the underlying issue/fix?

**Comment by dobber1** [comment]
My working database is now  'Bob & Cathy Finance.mmb but it hasn't changed anything in my dashboard / home screen. Still reconciled Net Worth Total at Top of Homepage, Don't Match Reconciled Acct. Totals with the rest of the home page.

This is with the new version 1,6.4.. Version 1.6.3 this problem did not exist. Top of home page matched acct. totals below on the home page. Its only the net worth reconciled total at top of screen that is wrong (see above screenshot ).

I  tried deleting some of my accounts one at a time just to see what the net worth reconciled total would do. After deleting my
checking account and all of my stock holdings that total is now the same as the totals with the saving accounts that are still there untouched. 
 
Version 1.6.3 this problem did not exist. It seems to me there is something in my checking and or stock holdings that's changing the net worth reconciled total at the top of the page. Everything else in my accounts seams to be working fine.

Thank You for taking that time for looking into this matter. If I can help with anything else please let me know.

**Comment by dobber1** [comment]
My working database is now 'Bob & Cathy Finance.mmb but it hasn't changed anything in my dashboard / home screen. Still reconciled Net Worth Total at Top of Homepage, Don't Match Reconciled Acct. Totals with the rest of the home page.

This is with the new version 1,6.4.. Version 1.6.3 this problem did not exist. Top of home page matched acct. totals below on the home page. Its only the net worth reconciled total at top of screen that is wrong (see above screenshot ).

I tried deleting some of my accounts one at a time just to see what the net worth reconciled total would do. After deleting my
checking account and all of my stock holdings that total is now the same as the totals with the saving accounts that are still there untouched.

Version 1.6.3 this problem did not exist. It seems to me there is something in my checking and or stock holdings that's changing the net worth reconciled total at the top of the page. Everything else in my accounts seams to be working fine.

Thank You for taking that time for looking into this matter. If I can help with anything else please let me know.

**Comment by n-stein** [comment]
Go to Reports -> Summary of Accounts -> Yearly. Check the "Share Accounts" column. Do you see negative balances?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/d5f541f4-fe5c-43f6-ab92-73a5f0131d83)

**Comment by migliosa** [comment]
Hi n-stein,

The problem is solved: by entering old investments (i.e. the retirement
fund) into MM Ex, I had set the accumulated amount in the 'Initial Balance'
field of the corresponding securities
 account props. From this version this field is (probably) not taken into
account in the report and I had to add the amount as a deposit at the top
of the account.

Thanks a lot for your support,

have a nice day
Sandro

Il giorno mer 28 giu 2023 alle ore 02:42 n-stein ***@***.***>
ha scritto:

**Comment by Heny67** [comment]
> Go to Reports -> Summary of Accounts -> Yearly. Check the "Share Accounts" column. Do you see negative balances?
> 

HI n-stein!
Although it is not closely related to the given error, the display of the amount of money is not set to thousands. How can I do this?


![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/46b086a7-085c-4e86-b992-a8c1650bee7c)

**Comment by migliosa** [comment]
"Reconciled Net Worth Total is negative" problem is solved: by entering old investments (i.e. the retirement
fund) into MM Ex, I had set the accumulated amount in the 'Initial Balance' field of the corresponding securities account props. By resetting this field to 0 and entering a Deposit  as the first movement in the account, everything went back to normal.

Thanks a lot for your support,


> Go to Reports -> Summary of Accounts -> Yearly. Check the "Share Accounts" column. Do you see negative balances?
> 
> ![image](https://user-images.githubusercontent.com/16599929/249314658-d5f541f4-fe5c-43f6-ab92-73a5f0131d83.png)

**Comment by dobber1** [comment]
To n-stein: This is dobber1. Still can't figure out why my dashboard totals are different at top of screen reconciled  net worth
compared to rest of page reconciled totals. 
 
This is my current dashboard screen. As you can see Totals in lower screen are $30,246.21 as the reconciled net worth amount is $38,525.59. That's a differance of  $8,279.38.

![20230630_115458](https://github.com/moneymanagerex/moneymanagerex/assets/121312562/100e4733-c42f-4534-99a1-51f98939ad95)

If I go to Reports / Summary of Accounts /yearly, for years 2022 & 2023 in the stocks column it shows 2 figures totaling -$5,624.33 in red type. I don't know where them amounts are coming from! Next screen I will show you what stocks I have.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/121312562/43e00eee-2aa8-4150-88e6-
e744a049c0dd)

This is some of my stocks screen. I indexed by unrealized gains/loss, As you can see there are only 4 red arrows to the left and gain/loss of $19.96. Most all my stock figures are accurate except dashboard stock gain/loss total is way to high.

![20230630_123244](https://github.com/moneymanagerex/moneymanagerex/assets/121312562/00f2a0a4-3493-40d5-a060-e9c03e8f6145)

I hope this will help you to find the reason for there's differences.
ps: don't really want to delete info in this database unless I have to.

Thanks for your help with this matter.

Robert

**Comment by dobber1** [comment]
Sorry, I see the Reports / Summary of Accounts / yearly: didn't open, I will try again.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/121312562/8d29f7bc-a37c-4ce4-8bff-9677cf40b43b)
