### ISSUE TITLE
Money format question

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#6074]
MMEX version:
 - [x] 1.6.4
 - [ ] 1.6.5 Beta
 - [ ] 1.6.6
 - [ ] 1.6.7
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
Hi All!
Where can it be set so that the money is displayed separately (separation in thousands) and that the money is not displayed at the front but at the end of the amount (123Ft)? At the moment, it is written together almost everywhere.

![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/04bde706-5279-42a2-b5a9-bf09c6eb0ec5)

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
1. In Options, set the locale to blank:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/1e1716ba-4d7d-4b44-a8df-f34ca8b94d59)

<br>

2. Tools | Organise Currency (or click on the icon).

Set Symbol Location to Suffix.
Grouping Char (for 1000s grouping) to Space or Comma as you wish.
Scale to 2 (for example) if you want to see decimal places.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/65d9b7c8-ee60-4735-a2dd-97aaac579c70)

**Comment by Heny67** [comment]
Thanks for the reply.
The thousands separator is set to a space, but it still doesn't display it that way, even after restarting.

![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/96a6dfb6-ba3d-4f35-a6d8-731a32555abf)

**Comment by tactilis** [comment]
> The thousands separator is set to a space, but it still doesn't display it that way, even after restarting.

That's odd. It's works here (MMEX 1.6.4, Windows in English):

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/1302ecd8-32e0-4496-a98a-2eb162a94bee)

The Shown As field updates as expected if I change between None/Dot/Comma/Space Grouping Char.

Can anyone else reproduce the problem @Heny67 is seeing on Linux in Hungarian?

**Comment by Heny67** [comment]
The mmex 1.6.3 verzo is still running on my laptop, it works fine there. It's also ubuntu 22.04, both places have the same currency manager settings in mmex.

**Comment by tactilis** [comment]
> The mmex 1.6.3 verzo is still running on my laptop, it works fine there.

Are you able to install 1.6.4 separately on your laptop to see whether it's a 1.6.3 vs 1.6.4 issue, or whether it has something to do with the Linux environments on your laptop vs desktop?

**Comment by Heny67** [comment]
It happened. Installed 1.6.4 on my laptop, same error.

**Comment by tactilis** [comment]
So the buggy behaviour _appears_ to be:

1.6.3 on Linux - Works OK

1.6.4 on same Linux PC as above - Grouping Char has no effect on display of number

1.6.4 on Windows - Works OK


There may, of course, be other factors involved.

**Comment by Heny67** [comment]
I ran this version on linux under wine and it works fine. (mmex-1.6.5-Beta.1-win64-portable)

**Comment by ovari** [comment]
> Can anyone else reproduce the problem @Heny67 is seeing on Linux in Hungarian?

Yes, with Linux Mint 21.2 Cinnamon.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/c6101882-6af2-49c5-ac1e-9233ce75584e)

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Jul 19 2023 19:40:21
• Database version: 19 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.2 "victoria"
• Linux 5.15.0-76-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by ovari** [comment]
For `Currency Code` = `HUF`, can the default `Symbol Location` = `Suffix`?

What do you think?

Thank you

**Comment by ovari** [comment]
Thousands grouping does not work for AUD either.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/2aad3e72-ee78-4ad0-9855-03161dd4df45)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/da7b9512-309a-4eae-80d2-53b7562e2e8c)

**Comment by vomikan** [comment]
By default, I have like this:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/f194dfe2-3024-4f4f-a57e-b79fdfdf3996)

**Comment by ovari** [comment]
@vomikan which GNU/Linux distro are you using?

**Comment by vomikan** [comment]
> GNU/Linux distro are you using?

Windows

**Comment by n-stein** [comment]
I think that should fix the missing thousands separator issue.

**Comment by ovari** [comment]
> I think that should fix the missing thousands separator issue.
> 
> @Heny67 @ovari Please test once #6353 is merged.

Verified fixed. Thank you

Sorry for the late reply.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/eb59f091-7b9c-4b1a-b447-13a9984bb229)

```
Money Manager Ex
• Verzió: 1.7.1-Beta.1 64 bites
• Készítési időpont: márc. 2 2024, 13:48:04
• Adatbázis verziója: 19 (aes128cbc)
• Git-végrehajtás: 138dc6b58 (2024-03-02)
• Git-ág: master
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.28.2
• GNU Make 4.4.1
• GCC 13.2.0
Fut a következőn:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-97-generic x86_64
• X-Cinnamon (X11)
• Rendszer területi beállítása: en_AU.UTF-8
• Felhasználói felület nyelve: hu_HU.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by Heny67** [comment]
The thousands separation still does not work for transaction reports.

![240521](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/1ef8e91a-b9b4-4985-a9d0-ef9e9d7640cb)

![Névtelen](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/714fc806-a2bd-4459-b7ee-5df28fbfd911)
