### ISSUE TITLE
WebView (Overview/Charts) broken with WebKitGTK 2.42

### ISSUE THREAD

**Issue by moritzhoewer** [moneymanagerex/moneymanagerex#6214]
MMEX version:
 - [x] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux  (ArchLinux)

# Description of the bug
A blank gray area is shown instead of the overview page or the charts. The rest of the UI is fine and so are tables (e.g. Transaction lists)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Start MMEX.

Expected result:
The Overview page is shown.

Actual result:
A blank gray area is shown.

# Additional information
I performed a system update and then the same issue that we had before in #4269 appeared again - the overview as well as the charts render as a blank gray area in MMEX. The generated HTML files in `/tmp` are fine and render correctly when opened in a regular Webbrowser (Firefox in my case).

The fix from last time - removing a file and re-generating the local MIME database, was still in place on my system and did not fix the issue this time. When looking into the updates, I saw that WebKitGTK (pacman packages `webkit2gtk` and `webkit2gtk-4.1`) was updated from 2.40.5 to 2.42.1. Downgrading the packages back to 2.40.5 fixed the issue for me.

**Comment by moritzhoewer** [comment]
I can live with the downgraded WebKitGTK.  I mainly wrote this bug report in case someone else with a bleeding-edge system runs into this issue as well.

According to https://webkitgtk.org/news.html there were also some versions in-between 2.40.5 and 2.42.1 - I did not (yet) try to pin down which exact version triggers the issue.

**Comment by Xrizoo** [comment]
> I can live with the downgraded WebKitGTK. I mainly wrote this bug report in case someone else with a bleeding-edge system runs into this issue as well.
> 
> According to https://webkitgtk.org/news.html there were also some versions in-between 2.40.5 and 2.42.1 - I did not (yet) try to pin down which exact version triggers the issue.

How did you downgrade WebKitGTK? I have Linux Mint (or underwear Ubuntu) and have no way to do that. I've tried with synaptic and apt-get but it no offer me to downgrade in any way.
Thanks in advance

**Comment by jota2016** [comment]
> > I can live with the downgraded WebKitGTK. I mainly wrote this bug report in case someone else with a bleeding-edge system runs into this issue as well.
> > According to https://webkitgtk.org/news.html there were also some versions in-between 2.40.5 and 2.42.1 - I did not (yet) try to pin down which exact version triggers the issue.
> 
> How did you downgrade WebKitGTK? I have Linux Mint (or underwear Ubuntu) and have no way to do that. I've tried with synaptic and apt-get but it no offer me to downgrade in any way. Thanks in advance

You can simply download the packages from the repository and force the installation.

**Comment by Xrizoo** [comment]
> > > I can live with the downgraded WebKitGTK. I mainly wrote this bug report in case someone else with a bleeding-edge system runs into this issue as well.
> > > According to https://webkitgtk.org/news.html there were also some versions in-between 2.40.5 and 2.42.1 - I did not (yet) try to pin down which exact version triggers the issue.
> > 
> > 
> > How did you downgrade WebKitGTK? I have Linux Mint (or underwear Ubuntu) and have no way to do that. I've tried with synaptic and apt-get but it no offer me to downgrade in any way. Thanks in advance
> 
> You can simply download the packages from the repository and force the installation.

Hi jota2016,

Thanks for you response... I'll try your suggestion but a lot of dependencies to solve appears constantly on every step... I give up. 

Solved in the way I hate the most... Sent it to a Windows virtualization and waiting for a fixed future versión.

Anyway, thanks a lot four your help!!!.

**Comment by Xrizoo** [comment]
> > I can live with the downgraded WebKitGTK. I mainly wrote this bug report in case someone else with a bleeding-edge system runs into this issue as well.
> > According to https://webkitgtk.org/news.html there were also some versions in-between 2.40.5 and 2.42.1 - I did not (yet) try to pin down which exact version triggers the issue.
> 
> How did you downgrade WebKitGTK? I have Linux Mint (or underwear Ubuntu) and have no way to do that. I've tried with synaptic and apt-get but it no offer me to downgrade in any way. Thanks in advance

Well, I figured I wasn't going to give up. I tried another basic distribution: Debian... and it works! What's more, I've tested with Linux Mint Debian Edition and it works perfectly with the libwebkitgtk-6.0.4/stable-security 2.42.1 library :-)
I imagine that the problem is not in the library but in the forced dependencies or in some high security restriction or simply in a bug that I can't identify.
Saying goodbye to the Ubuntu version, I don't like unpleasant surprises, welcome back Debian (with the Mint ornaments).

Translated with www.DeepL.com/Translator (free version)

**Comment by Hyperspeed1313** [comment]
Having the same problem on Fedora with the Flatpak build. Not at all sure how to resolve it. Still an issue in the 1.7.0 beta builds. More details in #6258

**Comment by Hyperspeed1313** [comment]
Downgrading the webkit version on my Fedora system didn't help. I don't know that it even makes a difference (is the Flatpak using my system's webkit verison or does it ship its own?)

**Comment by jota2016** [comment]
If it helps, on Fedora 38 I have downgraded this:

javascriptcoregtk4.0-2.42.1-1.fc38.x86_64 
javascriptcoregtk4.1-2.42.1-1.fc38.x86_64
webkit2gtk4.0-2.42.1-1.fc38.x86_64
webkit2gtk4.1-2.42.1-1.fc38.x86_64

Now I have this installed: 

javascriptcoregtk4.0-2.40.0-2.fc38.x86_64
javascriptcoregtk4.1-2.40.0-2.fc38.x86_64
webkit2gtk4.0-2.40.0-2.fc38.x86_64
webkit2gtk4.1-2.40.0-2.fc38.x86_64

I manually downloaded the packages and forced the downgrade.

**Comment by mfep** [comment]
> If it helps, on Fedora 38 I have downgraded this:
> 
> javascriptcoregtk4.0-2.42.1-1.fc38.x86_64 javascriptcoregtk4.1-2.42.1-1.fc38.x86_64 webkit2gtk4.0-2.42.1-1.fc38.x86_64 webkit2gtk4.1-2.42.1-1.fc38.x86_64
> 
> Now I have this installed:
> 
> javascriptcoregtk4.0-2.40.0-2.fc38.x86_64 javascriptcoregtk4.1-2.40.0-2.fc38.x86_64 webkit2gtk4.0-2.40.0-2.fc38.x86_64 webkit2gtk4.1-2.40.0-2.fc38.x86_64
> 
> I manually downloaded the packages and forced the downgrade.

Hi! @jota2016 I assume this must be the rpm version, not the Flatpak one. To my understanding, the Flatpak distribution uses the libraries of the underlying Flatpak platform, not the system installed ones.

**Comment by jota2016** [comment]
> > If it helps, on Fedora 38 I have downgraded this:
> > javascriptcoregtk4.0-2.42.1-1.fc38.x86_64 javascriptcoregtk4.1-2.42.1-1.fc38.x86_64 webkit2gtk4.0-2.42.1-1.fc38.x86_64 webkit2gtk4.1-2.42.1-1.fc38.x86_64
> > Now I have this installed:
> > javascriptcoregtk4.0-2.40.0-2.fc38.x86_64 javascriptcoregtk4.1-2.40.0-2.fc38.x86_64 webkit2gtk4.0-2.40.0-2.fc38.x86_64 webkit2gtk4.1-2.40.0-2.fc38.x86_64
> > I manually downloaded the packages and forced the downgrade.
> 
> Hi! @jota2016 I assume this must be the rpm version, not the Flatpak one. To my understanding, the Flatpak distribution uses the libraries of the underlying Flatpak platform, not the system installed ones.

Hi @mfep. That's right, I mean the OS rpm, not flatpak.

**Comment by Hyperspeed1313** [comment]
That fix worked for me as well. Removed the Flatpak install, installed the Fedora rpm from release 1.6.4, still had problem. Downgraded the javascriptcoregtk and webkit2gtk packages and now it's working.

Also used ```dnf versionlock``` so they don't get upgraded.

**Comment by Hyperspeed1313** [comment]
Interestingly enough, I decided to move to Nobara (Fedora + Glorious Eggroll tweaks) and don't encounter this problem anymore when using the RPM package, even though it's still Fedora 38 underneath and with the newer libwekit2gtk 2.42-1. Still having the problem with the Flatpak.

**Comment by jota2016** [comment]
New testing.
With flatpak, Fedora 38 and with v2.40 of webkit2gtk4 and javascriptcoregtk4, the problem persists.
In a clean installation of Fedora 39, with v2.42 of webkit2gtk4 and javascriptcoregtk4, with flatpak the charts are displayed perfectly.

**Comment by jota2016** [comment]
Upgraded Fedora 38 to Fedora 39. Flatpak mmex is working fine with latest packages and libraries.

**Comment by Hyperspeed1313** [comment]
> Upgraded Fedora 38 to Fedora 39. Flatpak mmex is working fine with latest packages and libraries.

Weird edge-case with how Flatpak gets packaged for Fedora 38 then?

**Comment by CorneliaXaos** [comment]
It's not just Fedora 38.  Pop!_OS 22.04 LTS here.  It wasn't happening a month ago and now it's no longer showing reports or the dashboard.

**Comment by pshchelo** [comment]
Looks like this is related to either windowing system (x11 vs Wayland) or Nvidia specifically:

I have tried on two systems;
Notebook: Ubuntu 22.04, Intel HD graphics with no proprietary drivers, Wayland, MMEX 1.7.0 installed as Flatpak - everything works
Desktop: Ubuntu 22.04, Nvidia graphics with proprietary drivers v535, x11, MMEX 1.7.0 installed as Flatpak - Overview and Charts are not rendered, with the following logged when one tries to open e.g. the Overview screen:
```
** (mmex:2): CRITICAL **: 23:15:24.252: Cannot register URI scheme memory more than once
Gtk-Message: 23:15:24.351: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:15:24.352: Failed to load module "canberra-gtk-module"
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1649x928: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1649x928: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1649x928: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

**Comment by pshchelo** [comment]
looks related, fixed (or at least possible to workaround for) in webkitgtk 2.41.3
https://bugs.webkit.org/show_bug.cgi?id=254807

**Comment by PMaff** [comment]
See reflex-frp/reflex-platform#735
Can you, @moritzhoewer and others, try:
export WEBKIT_DISABLE_COMPOSITING_MODE=1

See
https://github.com/moneymanagerex/moneymanagerex/issues/6396#issuecomment-1913278454

**Comment by Xrizoo** [comment]
Well, I know where the problem lies (at least for me).
With a fresh installation of Linux MMEX it worked fine, so I continued installing libraries. When I tested the application again it crashed again and it was just after installing the NVIDIA proprietary driver, I simply uninstalled it and reinstalled the open source Nouveau and.... voila! it works correctly. I already have the culprit.

**Comment by moritzhoewer** [comment]
> Can you, @moritzhoewer and others, try: export WEBKIT_DISABLE_COMPOSITING_MODE=1

Sorry for the late reaction - ever since this issue, I have held back on updating the webkit2gtk libraries. I have just now done a full system update (still on Arch Linux) and everything still works as expected without any workarounds. So specifically, I did **NOT** have to export the environment variable.

From my side, the issue seems to be resolved now. Unfortunately, I have no idea what exactly did the trick. Since I last looked into this in September, hundreds if not thousands of packages have been updated on my system.

For reference to what has been named here so far:
My system is Arch Linux with i3 as window manager (so X11), I have an NVIDIA GTX 970 card and I am running the nvidia proprietary drivers (I need them because I sometimes need CUDA).

Regarding the other packages that have been mentioned here:
* webkit2gtk and webkit2gtk-4.1 are now on version `2.42.5-1`  
  (this could fit to what @pshchelo mentioned above - I am guessing this version has the mentioned workaround/fix)
  > looks related, fixed (or at least possible to workaround for) in webkitgtk 2.41.3
  > https://bugs.webkit.org/show_bug.cgi?id=254807
* the nvidia drivers are version `545.29.06-18`

and MMEX has been updated at some point in between and is now on version `1.7.0`

**Comment by PMaff** [comment]
On a Ubuntu 22.04 virtual machine with all newest updates
I get
```
"checking for WEBKIT... configure: WARNING: webkit2gtk-4.1 not found, falling back to webkit2gtk-4.0
checking for WEBKIT... yes"
```
when configuring wxWidget 3.2.4 this way:
`3_2_4/wxWidgets/gtkbuild$ ../configure --disable-shared --enable-stl --enable-utf8only --enable-intl  --enable-xlocale  --enable-webviewwebkit --with-gtk=3 --enable-webview --enable-cxx11 --with-cxx=11 --enable-unicode`


So I installed webkitgtk-4.1, configured and got
`"checking for WEBKIT... yes"`
But after compiling and compiling the samples and running a sample I get:
```
"gtkbuild$ ./samples/webview/webview

(webview:80184): libsoup-ERROR **: 19:09:26.251: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
Trace/breakpoint trap (core dumped)"
```
There are dependencies on libsoup3 from webkitgtk-4.1 and 
3_2_4/wxWidgets$ more ./build/cmake/modules/FindLIBSOUP.cmake 
has:
```
# - Try to find LibSoup 2.4
# This module defines the following variables:
#
#  LIBSOUP_FOUND - LibSoup 2.4 was found
#  LIBSOUP_INCLUDE_DIRS - the LibSoup 2.4 include directories
#  LIBSOUP_LIBRARIES - link these to use LibSoup 2.4

SET(LIBSOUP_VERSION 2.4)
if(DEFINED LIBSOUP_FIND_VERSION)
    SET(LIBSOUP_VERSION ${LIBSOUP_FIND_VERSION})
endif()
```

So wxWidget 3.2.4 on one hand says that it is missing webkit2gtk-4.1 and falling back to webkit2gtk-4.0
if 4.1 is not there, but on the other hand 4.1 is causing runtime problems with
"libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported."
:-(

Uninstalling webkit2gtk-4.1 and then working with 4.0 removes the runtime error about libsoup3
and lets me run the sample 
3_2_4/wxWidgets/gtkbuild$ ./samples/webview/webview
with 
"20:02:46: Backend: wxWebViewWebKit Version: webkit2 2.42.5
20:02:46: User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
but in the window there also is no content.

Loading Google results in an endless load.
I have to CTRL-c the sample.

**Comment by moritzhoewer** [comment]
Update to my earlier comment: One of the recent system updates made the issue re-appear for me. Since I don't use MMEX on a daily basis, I can't really pinpoint the issue.

However, `WEBKIT_DISABLE_COMPOSITING_MODE=1` worked for me and I have an NVIDIA card.
