### ISSUE TITLE
Fatal error occurs when entering date value exceeding the specified value

### ISSUE THREAD

**Issue by DevAnyKR** [moneymanagerex/moneymanagerex#6924]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1 RC1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

![image](https://github.com/user-attachments/assets/ff660191-155a-4972-91fe-568a640abbb5)

![image](https://github.com/user-attachments/assets/802dd7ab-005b-49e5-9dff-0f1dc03897e9)

the error occurs when the date value goes from 3001-01-01 to the next month.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. open transaction dialog
2. Enter 3001-01-01 and click Next Month. Or enter the value that exceeds it directly.

Expected result:

normal...

it should also handle exceptions when accidentally enter the wrong date value.

Actual result:

Critical Error.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
I can't reproduce the crash. Running wxWidgets with debug enabled I receive assertion failures trying to exceed Dec 31, 3000 due to limitations of the _mktime64 function, but if I "Continue" the program will run normally. Is it still crashing for you?

**Comment by DevAnyKR** [comment]
error always appears. Reproducible 100% 😢

**Comment by n-stein** [comment]
That fix restricts the maximum date you can enter in the date controls to DATE_MAX which is set as 2999-12-31 23:59:59.

**Comment by n-stein** [comment]
Fixed a bug where if the stored date was > 2999-12-31T00:00:00 it wouldn't set the date portion of the control to 2999-12-31.

**Comment by DevAnyKR** [comment]
@n-stein 

I just downloaded the latest build. 1.9.0 RC1
this issue is not fixed. Still when I click on the calendar to change the date to after 3001-01-31, the process is force-quitted.
100% reproducible. Win 11 x64

**Comment by n-stein** [comment]
You can't test the latest build, this change is not yet merged to master. You have to test with the commit-specific build. 

Try https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/51302130

**Comment by DevAnyKR** [comment]
> Try https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/51302130

same error.

Typing the wrong date is a rare mistake, so you can fix it later. I'm most looking forward to the solution for #6907 😁

**Comment by n-stein** [comment]
> same error

Are you able to enter a date after 12-31-2999 in that beta build? When I try to enter a greater value (through typing, spin button, or calendar drop-down) it immediately reverts to 12-31-2999.

**Comment by DevAnyKR** [comment]
> Are you able to enter a date after 12-31-2999 in that beta build? When I try to enter a greater value (through typing, spin button, or calendar drop-down) it immediately reverts to 12-31-2999.

never....
(my datetime format is.  YYYY-MM-DD)
Error occurs from 3001-01-20. Normal input is possible until 3001-01-19.
12-31-2999 -> click next or press Up key on day value -> 3000-01-01.  is OK. ~~~ 3001-01-19 is OK.
![image](https://github.com/user-attachments/assets/9e372a17-6d42-4027-8733-25019fba13ed)
(monday)
-> click next -> Terminate MMEX.exe Proccess  (3001-01-20)
![image](https://github.com/user-attachments/assets/c7cb6b8d-062e-47ea-a8c4-e7fdbe1a2087)

**Comment by n-stein** [comment]
Sorry, still struggling with understanding what is occurring on your system. 

I'm using the latest beta

• Version: 1.9.0-RC.1 64-bit
• Built on: Jan 13 2025 11:38:10
• Database version: 19 (aes256cbc-hmac-sha512)
• Git commit: 4ac9f02 (2025-01-13)

I can't physically enter a date with a year greater than 2999 through any method -- direct key, calendar dropdown, spin button. The max date I am able to enter is 2999-12-31. Here is how it is working for me:

![mmex_nJSHAmO15u](https://github.com/user-attachments/assets/21bdce64-dd30-4dbf-a8ae-299e3ce859af)

Is this not how it works for you?

**Comment by DevAnyKR** [comment]
![image](https://github.com/user-attachments/assets/c54fc131-821b-4e98-953b-e69f98981565)

Merge pull request #7116.
Confirmed normal operation.
Thank you for your hard work.
