### ISSUE TITLE
Feedback to stock v2

### ISSUE THREAD

**Issue by JoshuaLampert** [moneymanagerex/moneymanagerex#7412]
I have tested the new stock v2 (I didn't try assets as I'm not using those) as announced here: https://forum.moneymanagerex.org/viewtopic.php?t=11385.
First of all, thanks for the great work! I think this simplifies dealing with shares and brings some advantages compared to the previous version.

I do have one issue though. As explained in the [blog entry](https://moneymanagerex.org/blog/mmex-stock-v2-preview-and-changes/#5-deprecation-of-transfer-concept) the "Transfer" concept for investments has been deprecated. This has, e.g., the consequence that all of the share transactions are now considered in the reports (e.g., categories, forecast, incomes vs. expenses, ...). For me a share transaction is just a change in the investment type, but not a deposit or withdrawal. Therefore, counting share transactions as transfers (and thus not displaying them in the reports) would be more reasonable to me. I suggest to have either the option to mark a share transaction as transfer (as it was before) or to have a global switch to exclude all share transactions in the reports.

I have a few other smaller comments/questions:

1. Double-clicking on a share transaction in the cash ledger doesn't show the selected category in the drop down menu.
2. I think, this has been the case before, but I noticed this when I tried out the new version. In the summary of accounts report the money in an investment account, which is not invested in stock (what is called "Cash Balance" in the new version), is not taken into account. Could this be put in a new column in the table and as a new color in the bar of the diagram? In my case, I transferred some money from a bank account to an investment account at the end of a month and then bought some stock in the beginning of the next month. Now I see a drop of in the balance in this specific month because this additional money on the investment account is not counted.
3. When I create a new stock investment the "Share lot" (and also the "Number") in the "Add Share Transaction" menu has a strange value (1744403120085411 in my case). This looks like a bug to me. A related question regarding the "Number" field of share transactions: If I understand correctly, before this was automatically filled with the name of the investment account and now it is automatically filled with the number and stock symbol. Can I, in principle, put anything in the "Number" field and these are only suggestions (which I like), or are they needed for anything? I.e., can I safely change the number field of the old share transactions to follow the new scheme for consistency?
4. This is just a remark: In addition to changing the Transaction Account ID of the old share transactions to the Investment Account ID, I also needed to change the initial balance of the investment accounts to account for the (in my case non-zero) initial balances of the share accounts. IIUC, otherwise, after adjusting their transfers and deleting them, there would be a wrong balance on the investment account because the initial balances are "forgotten". Maybe you could just add this to [the blog post](https://moneymanagerex.org/blog/mmex-stock-v2-preview-and-changes/#5-deprecation-of-transfer-concept) or document this somewhere so others know that the initial balances potentially need to be adjusted to migrate to stock v2.

I hope this helps and can improve stock v2 even further. If anything is unclear, please ask. I am happy to discuss further.
Thanks again for the great work!

**Comment by guanlisheng** [comment]
Thanks, @JoshuaLampert, for the detailed feedback, and let's go through them one by one
1. Can't be reproduced. I haven't gotten the question clear yet.
2. That's a good catch. The cash balance is missing in `Reports -> Stocks Report -> Summary`, and we will consider including it. `Stock Portfolios -> your investment account` has all kinds of metrics
3. This long number (e.g., 1744403120085411) is the share LOT ID, just for reference so far. 
4. Another great catch; I will add it to the blog post soon

In terms of **`transfer`**,  it was too complicated and broke some rules, and deposit or withdrawal would reflect the real world better.
1. A buy trade will trigger the following flow: investment account (withdrawal, -) -> stocks (buy/increasing, invested +)
2. A sell trade will trigger the following flow: investment account (deposit, +) <- stocks (sell/decreasing, invested -)
Hence, can you rethink whether this would solve your use cases?

**Comment by JoshuaLampert** [comment]
Thanks @guanlisheng for the quick response!

1. Sorry, I was a bit unclear. This is just a small point. To reproduce, here is a test database:  [test.zip](https://github.com/user-attachments/files/19718988/test.zip) and a screenshot showing the behavior:

![Image](https://github.com/user-attachments/assets/97a4896d-90fc-439f-a3ac-b2d60ade25e6)

As you can see, the category (in this case "Investment") is not pre-selected in the "Edit Share Transaction" menu.
2. I saw #7413, which I tried already out of interest. I can see a column "Investment Accounts" now, which is nice. Maybe you are still working on it, but I saw that now the amounts (all amounts, not just the investment accounts) are way too high. It seems like the numbers are wrongly accumulated from month to month (or from year to year). Could you maybe double-check this? If you can't reproduce this behavior, I can try to build a test database showing this behavior.
3. Ah, I see. So do I understand correctly that previously the share lot ID was empty by default and in the new version gets some reference value? Also: I can edit the "Number" field as I want, right? It doesn't need to have the share lot ID in it. This is just a suggestion?
4. I saw https://github.com/moneymanagerex/moneymanagerex.github.io/commit/ccac285126099362fdf47be9a4efa32709677b96. Thanks!

Regarding the transfer: I understand that with the new system a buy trade will result in a withdrawal of the investment account and similarly for sell trades as deposits, but I'm still not happy with this solution.  I don't see buying shares as expenses (after buying shares, "the money is still mine" in a sense), so I definitely don't want to see them in the reports as it would distort the overview of my real expenses. If it is too complicated to allow the opportunity to mark share transactions as transfer, would it be easier to add a setting, e.g., in the general "View" settings, which allows the user to filter out all share transactions in the reports?

**Comment by guanlisheng** [comment]
Aha, 
1. I got this, but your database works well on my side (Mac)..
2. Just fixed the bug (#7415).  `Total` column as a separator, the left amounts are cash balances and the right ones are market value. #
3. Yes, this is just a suggestion.  Is there a good candidate here? 
4. Thank you.

It's a great idea to have an option to include/exclude the trade transactions in the reports. 
For investment/asset accounts, they have both cash balance and market value. 
The former is identical to a bank account, and the latter is just market value instead of your money.

**Comment by JoshuaLampert** [comment]
Thanks again for the reply @guanlisheng!
1. That's interesting. I'm on Ubuntu. With version 1.9.0 this works fine for the share transactions.
2. I just tried your fix in #7415 with [this flatpak build](https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/2564/workflows/3f25cf80-bfa2-4421-aed0-a3126648ad1e/jobs/2552/artifacts). I'm sorry, but I think there is still an issue. It seems like the amounts are wrongly summed up. For example, in the "Monthly" Summary of Accounts report, the first month is correct. However, the second month seems to display the sums (in each column) of the amounts of  the first and the second month, but it should not sum them up. In the third month the sum of the final amount in the third month is added up with the final amount in the second (or first?) month. I.e. the balances grow very fast. Can you reproduce this issue and do you know what I mean? If not, I can build a small database and share a screenshot.
3. Ok, then I think it's fine. Personally, I find the number a bit confusing, but if you can edit it, I guess it's fine.
> It's a great idea to have an option to include/exclude the trade transactions in the reports.

So would you consider implementing this feature? This would be really great! Again, I can help with testing.

**Comment by guanlisheng** [comment]
1. I will keep an eye on it, and this might be a platform-specific issue. 
2. found the root cause #7417 
3. It makes sense; I will update it as the combination of the company and stock symbol.

Yup, will add an option, and it might take time. Stay tuned.

**Comment by JoshuaLampert** [comment]
1. Sounds good. This is not so urgent.
2. Yes, #7417 fixed it. Thanks a lot!
3. Sounds good. This is also not urgent.

> Yup, I will add an option, but it might take time. Stay tuned.

Great! I'm looking forward to it. As another workaround I found that, e.g., in the categories reports, I can filter by accounts to not include the investment accounts (see also point 6. below). I would still prefer the option we discussed.

While trying further, I noticed a few other things (related to stock, but not necessarily related to stock v2 specifically):

5. In the Dashboard under "Stocks" it shows the total balance of the investment accounts. Would it make sense to split this up into the market value and the cash balance (in addition to showing the sum of both)?
6. I noticed that the Investment accounts are not listed in the drop down menu, when filtering the accounts in the reports (e.g. "Where the Money goes"), i.e. selecting "All accounts" gives a different result than selecting "Specific Accounts..." and then checking all accounts in the list. This feels a bit unintuitive. Is there a good reason for not including the investment accounts in these filters?
7. This is probably largely unrelated to stock v2, but I'll also mention it here. In the Stock Portfolio, I would like to have the option to hide certain stock investments. Let's say I sold some stock meaning I have a "Share Total" of 0. I don't want to see this entry in my list of stocks anymore. At first, I thought deleting the stock investment would do the job, but this also deletes the corresponding stock transactions, but I would like to still see them in my history. Is there currently a way to achieve what I want or would an option to hide the investments be a viable solution? It would also be nice to then find a way to un-hide it again (I'm not totally sure how this would be done because if the entry is hidden, you cannot click on it anymore to un-hide it, but I'm optimistic that there will be some way to realize this).

**Comment by guanlisheng** [comment]
do like such detailed feedback.

5. This would be implemented after #7419 
6. This is addressed by #7418 

3, 7, and `transfer` are still in the to-do list.

**Comment by JoshuaLampert** [comment]
And I really like your prompt reactions and fixes! This is making great progress! 😃 
I will test #7418 and #7419 soon.

**Comment by JoshuaLampert** [comment]
5. #7419 is exactly what I had in mind. Thanks!
6. With #7418, I see that we can now select "Investment" in the drop-down menu, which is good, but I am still missing the specific investment accounts under "Specific Accounts...". Could they also be added, please?

**Comment by guanlisheng** [comment]
6. The drop-down list issue has been addressed with an extra commit to #7419.  There were many tricky logic to hide the Investment account in legacy Stock v1 mode.

**Comment by JoshuaLampert** [comment]
Looks good! This resolves 6. 👍

**Comment by guanlisheng** [comment]
Item 3 and 7 are ready after #7422 

`asTransfer (option to exclude) ` would take longer as i thought.

**Comment by JoshuaLampert** [comment]
Thanks! Just tested #7422. This resolves items 3 and 7 👍

**Comment by guanlisheng** [comment]
Hi @JoshuaLampert , an update for `asTransfer`,  just restored the previous interface, and we can set/update it for each trade transaction now.

**Comment by JoshuaLampert** [comment]
That's great to hear @guanlisheng! I'll test it shortly and give feedback. Thanks a lot!

**Comment by JoshuaLampert** [comment]
Works like a charm. Thanks again. Now, all my issues have been addressed.
